// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: board_members.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoardMember = `-- name: CreateBoardMember :one
INSERT INTO board_members (club_id, member_id, user_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, club_id, member_id, user_id, position, created_at, updated_at
`

type CreateBoardMemberParams struct {
	ClubID   pgtype.UUID `json:"club_id"`
	MemberID pgtype.UUID `json:"member_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Position string      `json:"position"`
}

func (q *Queries) CreateBoardMember(ctx context.Context, arg CreateBoardMemberParams) (BoardMember, error) {
	row := q.db.QueryRow(ctx, createBoardMember,
		arg.ClubID,
		arg.MemberID,
		arg.UserID,
		arg.Position,
	)
	var i BoardMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoardMember = `-- name: DeleteBoardMember :exec
DELETE FROM board_members WHERE id = $1
`

func (q *Queries) DeleteBoardMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardMember, id)
	return err
}

const getBoardMember = `-- name: GetBoardMember :one
SELECT id, club_id, member_id, user_id, position, created_at, updated_at FROM board_members WHERE id = $1
`

func (q *Queries) GetBoardMember(ctx context.Context, id pgtype.UUID) (BoardMember, error) {
	row := q.db.QueryRow(ctx, getBoardMember, id)
	var i BoardMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardMembers = `-- name: GetBoardMembers :many
SELECT bm.id, bm.club_id, bm.member_id, bm.user_id, bm.position, bm.created_at, bm.updated_at,
       m.first_name, m.last_name, m.member_number,
       u.email
FROM board_members bm
JOIN members m ON bm.member_id = m.id
JOIN users u ON bm.user_id = u.id
WHERE bm.club_id = $1
ORDER BY m.last_name, m.first_name
`

type GetBoardMembersRow struct {
	ID           pgtype.UUID        `json:"id"`
	ClubID       pgtype.UUID        `json:"club_id"`
	MemberID     pgtype.UUID        `json:"member_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Position     string             `json:"position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	MemberNumber string             `json:"member_number"`
	Email        string             `json:"email"`
}

func (q *Queries) GetBoardMembers(ctx context.Context, clubID pgtype.UUID) ([]GetBoardMembersRow, error) {
	rows, err := q.db.Query(ctx, getBoardMembers, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardMembersRow
	for rows.Next() {
		var i GetBoardMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.MemberID,
			&i.UserID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.MemberNumber,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardMember = `-- name: UpdateBoardMember :one
UPDATE board_members
SET position = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, club_id, member_id, user_id, position, created_at, updated_at
`

type UpdateBoardMemberParams struct {
	ID       pgtype.UUID `json:"id"`
	Position string      `json:"position"`
}

func (q *Queries) UpdateBoardMember(ctx context.Context, arg UpdateBoardMemberParams) (BoardMember, error) {
	row := q.db.QueryRow(ctx, updateBoardMember, arg.ID, arg.Position)
	var i BoardMember
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberID,
		&i.UserID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
