// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  club_id, date, time, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, club_id, date, time, description, created_at, updated_at
`

type CreateEventParams struct {
	ClubID      pgtype.UUID `json:"club_id"`
	Date        pgtype.Date `json:"date"`
	Time        pgtype.Time `json:"time"`
	Description string      `json:"description"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ClubID,
		arg.Date,
		arg.Time,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Date,
		&i.Time,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1 AND club_id = $2
`

type DeleteEventParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.ClubID)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, club_id, date, time, description, created_at, updated_at FROM events
WHERE club_id = $1
ORDER BY date, time
`

func (q *Queries) ListEvents(ctx context.Context, clubID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Date,
			&i.Time,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, club_id, date, time, description, created_at, updated_at FROM events
WHERE club_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date, time
`

type ListEventsByDateRangeParams struct {
	ClubID   pgtype.UUID `json:"club_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByDateRange, arg.ClubID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Date,
			&i.Time,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
  date = $3,
  time = $4,
  description = $5,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, date, time, description, created_at, updated_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID `json:"id"`
	ClubID      pgtype.UUID `json:"club_id"`
	Date        pgtype.Date `json:"date"`
	Time        pgtype.Time `json:"time"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.ClubID,
		arg.Date,
		arg.Time,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Date,
		&i.Time,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
