// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clubs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClub = `-- name: CreateClub :one
INSERT INTO clubs (
  registered_association, name, type, category, number, 
  street_house_number, postal_code, city, name_extension, address_extension,
  tax_office_name, tax_office_tax_number, tax_office_assessment_period,
  tax_office_purpose, tax_office_decision_date, tax_office_decision_type
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16
)
RETURNING id, registered_association, name, type, category, number, street_house_number, postal_code, city, name_extension, address_extension, phone, email, tax_office_name, tax_office_tax_number, tax_office_vat_id, tax_office_assessment_period, tax_office_purpose, tax_office_decision_date, tax_office_decision_type, created_at, updated_at
`

type CreateClubParams struct {
	RegisteredAssociation     bool        `json:"registered_association"`
	Name                      string      `json:"name"`
	Type                      string      `json:"type"`
	Category                  pgtype.Text `json:"category"`
	Number                    pgtype.Text `json:"number"`
	StreetHouseNumber         pgtype.Text `json:"street_house_number"`
	PostalCode                pgtype.Text `json:"postal_code"`
	City                      pgtype.Text `json:"city"`
	NameExtension             pgtype.Text `json:"name_extension"`
	AddressExtension          pgtype.Text `json:"address_extension"`
	TaxOfficeName             pgtype.Text `json:"tax_office_name"`
	TaxOfficeTaxNumber        pgtype.Text `json:"tax_office_tax_number"`
	TaxOfficeAssessmentPeriod pgtype.Text `json:"tax_office_assessment_period"`
	TaxOfficePurpose          pgtype.Text `json:"tax_office_purpose"`
	TaxOfficeDecisionDate     pgtype.Date `json:"tax_office_decision_date"`
	TaxOfficeDecisionType     pgtype.Text `json:"tax_office_decision_type"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub,
		arg.RegisteredAssociation,
		arg.Name,
		arg.Type,
		arg.Category,
		arg.Number,
		arg.StreetHouseNumber,
		arg.PostalCode,
		arg.City,
		arg.NameExtension,
		arg.AddressExtension,
		arg.TaxOfficeName,
		arg.TaxOfficeTaxNumber,
		arg.TaxOfficeAssessmentPeriod,
		arg.TaxOfficePurpose,
		arg.TaxOfficeDecisionDate,
		arg.TaxOfficeDecisionType,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.RegisteredAssociation,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.Number,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.NameExtension,
		&i.AddressExtension,
		&i.Phone,
		&i.Email,
		&i.TaxOfficeName,
		&i.TaxOfficeTaxNumber,
		&i.TaxOfficeVatID,
		&i.TaxOfficeAssessmentPeriod,
		&i.TaxOfficePurpose,
		&i.TaxOfficeDecisionDate,
		&i.TaxOfficeDecisionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClub = `-- name: DeleteClub :exec
DELETE FROM clubs
WHERE id = $1
`

func (q *Queries) DeleteClub(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClub, id)
	return err
}

const getClubByID = `-- name: GetClubByID :one
SELECT id, registered_association, name, type, category, number, street_house_number, postal_code, city, name_extension, address_extension, phone, email, tax_office_name, tax_office_tax_number, tax_office_vat_id, tax_office_assessment_period, tax_office_purpose, tax_office_decision_date, tax_office_decision_type, created_at, updated_at FROM clubs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClubByID(ctx context.Context, id pgtype.UUID) (Club, error) {
	row := q.db.QueryRow(ctx, getClubByID, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.RegisteredAssociation,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.Number,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.NameExtension,
		&i.AddressExtension,
		&i.Phone,
		&i.Email,
		&i.TaxOfficeName,
		&i.TaxOfficeTaxNumber,
		&i.TaxOfficeVatID,
		&i.TaxOfficeAssessmentPeriod,
		&i.TaxOfficePurpose,
		&i.TaxOfficeDecisionDate,
		&i.TaxOfficeDecisionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstClub = `-- name: GetFirstClub :one
SELECT id, registered_association, name, type, category, number, street_house_number, postal_code, city, name_extension, address_extension, phone, email, tax_office_name, tax_office_tax_number, tax_office_vat_id, tax_office_assessment_period, tax_office_purpose, tax_office_decision_date, tax_office_decision_type, created_at, updated_at FROM clubs
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstClub(ctx context.Context) (Club, error) {
	row := q.db.QueryRow(ctx, getFirstClub)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.RegisteredAssociation,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.Number,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.NameExtension,
		&i.AddressExtension,
		&i.Phone,
		&i.Email,
		&i.TaxOfficeName,
		&i.TaxOfficeTaxNumber,
		&i.TaxOfficeVatID,
		&i.TaxOfficeAssessmentPeriod,
		&i.TaxOfficePurpose,
		&i.TaxOfficeDecisionDate,
		&i.TaxOfficeDecisionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClubs = `-- name: ListClubs :many
SELECT id, registered_association, name, type, category, number, street_house_number, postal_code, city, name_extension, address_extension, phone, email, tax_office_name, tax_office_tax_number, tax_office_vat_id, tax_office_assessment_period, tax_office_purpose, tax_office_decision_date, tax_office_decision_type, created_at, updated_at FROM clubs
ORDER BY name
`

func (q *Queries) ListClubs(ctx context.Context) ([]Club, error) {
	rows, err := q.db.Query(ctx, listClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.RegisteredAssociation,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.Number,
			&i.StreetHouseNumber,
			&i.PostalCode,
			&i.City,
			&i.NameExtension,
			&i.AddressExtension,
			&i.Phone,
			&i.Email,
			&i.TaxOfficeName,
			&i.TaxOfficeTaxNumber,
			&i.TaxOfficeVatID,
			&i.TaxOfficeAssessmentPeriod,
			&i.TaxOfficePurpose,
			&i.TaxOfficeDecisionDate,
			&i.TaxOfficeDecisionType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClub = `-- name: UpdateClub :one
UPDATE clubs
SET
  registered_association = $2,
  name = $3,
  type = $4,
  category = $5,
  number = $6,
  street_house_number = $7,
  postal_code = $8,
  city = $9,
  name_extension = $10,
  address_extension = $11,
  tax_office_name = $12,
  tax_office_tax_number = $13,
  tax_office_assessment_period = $14,
  tax_office_purpose = $15,
  tax_office_decision_date = $16,
  tax_office_decision_type = $17,
  updated_at = NOW()
WHERE id = $1
RETURNING id, registered_association, name, type, category, number, street_house_number, postal_code, city, name_extension, address_extension, phone, email, tax_office_name, tax_office_tax_number, tax_office_vat_id, tax_office_assessment_period, tax_office_purpose, tax_office_decision_date, tax_office_decision_type, created_at, updated_at
`

type UpdateClubParams struct {
	ID                        pgtype.UUID `json:"id"`
	RegisteredAssociation     bool        `json:"registered_association"`
	Name                      string      `json:"name"`
	Type                      string      `json:"type"`
	Category                  pgtype.Text `json:"category"`
	Number                    pgtype.Text `json:"number"`
	StreetHouseNumber         pgtype.Text `json:"street_house_number"`
	PostalCode                pgtype.Text `json:"postal_code"`
	City                      pgtype.Text `json:"city"`
	NameExtension             pgtype.Text `json:"name_extension"`
	AddressExtension          pgtype.Text `json:"address_extension"`
	TaxOfficeName             pgtype.Text `json:"tax_office_name"`
	TaxOfficeTaxNumber        pgtype.Text `json:"tax_office_tax_number"`
	TaxOfficeAssessmentPeriod pgtype.Text `json:"tax_office_assessment_period"`
	TaxOfficePurpose          pgtype.Text `json:"tax_office_purpose"`
	TaxOfficeDecisionDate     pgtype.Date `json:"tax_office_decision_date"`
	TaxOfficeDecisionType     pgtype.Text `json:"tax_office_decision_type"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClub,
		arg.ID,
		arg.RegisteredAssociation,
		arg.Name,
		arg.Type,
		arg.Category,
		arg.Number,
		arg.StreetHouseNumber,
		arg.PostalCode,
		arg.City,
		arg.NameExtension,
		arg.AddressExtension,
		arg.TaxOfficeName,
		arg.TaxOfficeTaxNumber,
		arg.TaxOfficeAssessmentPeriod,
		arg.TaxOfficePurpose,
		arg.TaxOfficeDecisionDate,
		arg.TaxOfficeDecisionType,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.RegisteredAssociation,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.Number,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.NameExtension,
		&i.AddressExtension,
		&i.Phone,
		&i.Email,
		&i.TaxOfficeName,
		&i.TaxOfficeTaxNumber,
		&i.TaxOfficeVatID,
		&i.TaxOfficeAssessmentPeriod,
		&i.TaxOfficePurpose,
		&i.TaxOfficeDecisionDate,
		&i.TaxOfficeDecisionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
