// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
  club_id, name, subdivision, parent_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, club_id, name, subdivision, parent_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	Subdivision pgtype.Text `json:"subdivision"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ClubID,
		arg.Name,
		arg.Subdivision,
		arg.ParentID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Subdivision,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = $1 AND club_id = $2
`

type DeleteDepartmentParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.ID, arg.ClubID)
	return err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, club_id, name, subdivision, parent_id, created_at, updated_at FROM departments
WHERE id = $1 AND club_id = $2 LIMIT 1
`

type GetDepartmentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, arg.ID, arg.ClubID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Subdivision,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, club_id, name, subdivision, parent_id, created_at, updated_at FROM departments
WHERE club_id = $1
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context, clubID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Subdivision,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET
  name = $3,
  subdivision = $4,
  parent_id = $5,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, name, subdivision, parent_id, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	Subdivision pgtype.Text `json:"subdivision"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.Subdivision,
		arg.ParentID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Subdivision,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
