// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
  club_id, name, content, category_id, description
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, club_id, name, category_id, description, created_at, updated_at
`

type CreateDocumentParams struct {
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	Content     []byte      `json:"content"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Description pgtype.Text `json:"description"`
}

type CreateDocumentRow struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Name        string             `json:"name"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// =====================
// Documents
// =====================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ClubID,
		arg.Name,
		arg.Content,
		arg.CategoryID,
		arg.Description,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentCategory = `-- name: CreateDocumentCategory :one

INSERT INTO document_categories (club_id, name, description, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, club_id, name, description, sort_order, created_at, updated_at
`

type CreateDocumentCategoryParams struct {
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

// =====================
// Document Categories
// =====================
func (q *Queries) CreateDocumentCategory(ctx context.Context, arg CreateDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, createDocumentCategory,
		arg.ClubID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1 AND club_id = $2
`

type DeleteDocumentParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.ClubID)
	return err
}

const deleteDocumentCategory = `-- name: DeleteDocumentCategory :exec
DELETE FROM document_categories
WHERE id = $1 AND club_id = $2
`

type DeleteDocumentCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteDocumentCategory(ctx context.Context, arg DeleteDocumentCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentCategory, arg.ID, arg.ClubID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, club_id, name, content, created_at, updated_at, category_id, description FROM documents
WHERE id = $1 AND club_id = $2
`

type GetDocumentParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.ClubID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Description,
	)
	return i, err
}

const getDocumentCategory = `-- name: GetDocumentCategory :one
SELECT id, club_id, name, description, sort_order, created_at, updated_at FROM document_categories
WHERE id = $1 AND club_id = $2
`

type GetDocumentCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetDocumentCategory(ctx context.Context, arg GetDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, getDocumentCategory, arg.ID, arg.ClubID)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentCategories = `-- name: ListDocumentCategories :many
SELECT id, club_id, name, description, sort_order, created_at, updated_at FROM document_categories
WHERE club_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListDocumentCategories(ctx context.Context, clubID pgtype.UUID) ([]DocumentCategory, error) {
	rows, err := q.db.Query(ctx, listDocumentCategories, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentCategory
	for rows.Next() {
		var i DocumentCategory
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.club_id, d.name, d.category_id, d.description, d.created_at, d.updated_at,
       dc.name AS category_name
FROM documents d
LEFT JOIN document_categories dc ON d.category_id = dc.id
WHERE d.club_id = $1
ORDER BY d.created_at DESC
`

type ListDocumentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	ClubID       pgtype.UUID        `json:"club_id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListDocuments(ctx context.Context, clubID pgtype.UUID) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCategory = `-- name: ListDocumentsByCategory :many
SELECT d.id, d.club_id, d.name, d.category_id, d.description, d.created_at, d.updated_at,
       dc.name AS category_name
FROM documents d
LEFT JOIN document_categories dc ON d.category_id = dc.id
WHERE d.club_id = $1 AND d.category_id = $2
ORDER BY d.created_at DESC
`

type ListDocumentsByCategoryParams struct {
	ClubID     pgtype.UUID `json:"club_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ListDocumentsByCategoryRow struct {
	ID           pgtype.UUID        `json:"id"`
	ClubID       pgtype.UUID        `json:"club_id"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]ListDocumentsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCategory, arg.ClubID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByCategoryRow
	for rows.Next() {
		var i ListDocumentsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET name = $3, category_id = $4, description = $5, updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, name, category_id, description, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID          pgtype.UUID `json:"id"`
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Description pgtype.Text `json:"description"`
}

type UpdateDocumentRow struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Name        string             `json:"name"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.CategoryID,
		arg.Description,
	)
	var i UpdateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCategory = `-- name: UpdateDocumentCategory :one
UPDATE document_categories
SET name = $3, description = $4, sort_order = $5, updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, name, description, sort_order, created_at, updated_at
`

type UpdateDocumentCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	ClubID      pgtype.UUID `json:"club_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) UpdateDocumentCategory(ctx context.Context, arg UpdateDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, updateDocumentCategory,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
