// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fee_mappings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeeAccountMapping = `-- name: CreateFeeAccountMapping :one
INSERT INTO fee_account_mappings (
  club_id, fee_type, club_bank_account_id
) VALUES (
  $1, $2, $3
)
RETURNING id, club_id, fee_type, club_bank_account_id, created_at, updated_at
`

type CreateFeeAccountMappingParams struct {
	ClubID            pgtype.UUID `json:"club_id"`
	FeeType           string      `json:"fee_type"`
	ClubBankAccountID pgtype.UUID `json:"club_bank_account_id"`
}

func (q *Queries) CreateFeeAccountMapping(ctx context.Context, arg CreateFeeAccountMappingParams) (FeeAccountMapping, error) {
	row := q.db.QueryRow(ctx, createFeeAccountMapping, arg.ClubID, arg.FeeType, arg.ClubBankAccountID)
	var i FeeAccountMapping
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.FeeType,
		&i.ClubBankAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeeAccountMapping = `-- name: DeleteFeeAccountMapping :exec
DELETE FROM fee_account_mappings
WHERE club_id = $1 AND fee_type = $2
`

type DeleteFeeAccountMappingParams struct {
	ClubID  pgtype.UUID `json:"club_id"`
	FeeType string      `json:"fee_type"`
}

func (q *Queries) DeleteFeeAccountMapping(ctx context.Context, arg DeleteFeeAccountMappingParams) error {
	_, err := q.db.Exec(ctx, deleteFeeAccountMapping, arg.ClubID, arg.FeeType)
	return err
}

const getFeeAccountMapping = `-- name: GetFeeAccountMapping :one
SELECT id, club_id, fee_type, club_bank_account_id, created_at, updated_at FROM fee_account_mappings
WHERE club_id = $1 AND fee_type = $2
`

type GetFeeAccountMappingParams struct {
	ClubID  pgtype.UUID `json:"club_id"`
	FeeType string      `json:"fee_type"`
}

func (q *Queries) GetFeeAccountMapping(ctx context.Context, arg GetFeeAccountMappingParams) (FeeAccountMapping, error) {
	row := q.db.QueryRow(ctx, getFeeAccountMapping, arg.ClubID, arg.FeeType)
	var i FeeAccountMapping
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.FeeType,
		&i.ClubBankAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeeAccountMappings = `-- name: ListFeeAccountMappings :many
SELECT fam.id, fam.club_id, fam.fee_type, fam.club_bank_account_id, fam.created_at, fam.updated_at, cba.name as bank_account_name, cba.iban
FROM fee_account_mappings fam
JOIN club_bank_accounts cba ON fam.club_bank_account_id = cba.id
WHERE fam.club_id = $1
`

type ListFeeAccountMappingsRow struct {
	ID                pgtype.UUID        `json:"id"`
	ClubID            pgtype.UUID        `json:"club_id"`
	FeeType           string             `json:"fee_type"`
	ClubBankAccountID pgtype.UUID        `json:"club_bank_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BankAccountName   string             `json:"bank_account_name"`
	Iban              string             `json:"iban"`
}

func (q *Queries) ListFeeAccountMappings(ctx context.Context, clubID pgtype.UUID) ([]ListFeeAccountMappingsRow, error) {
	rows, err := q.db.Query(ctx, listFeeAccountMappings, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeeAccountMappingsRow
	for rows.Next() {
		var i ListFeeAccountMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.FeeType,
			&i.ClubBankAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankAccountName,
			&i.Iban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeeAccountMapping = `-- name: UpdateFeeAccountMapping :one
UPDATE fee_account_mappings
SET club_bank_account_id = $3, updated_at = NOW()
WHERE club_id = $1 AND fee_type = $2
RETURNING id, club_id, fee_type, club_bank_account_id, created_at, updated_at
`

type UpdateFeeAccountMappingParams struct {
	ClubID            pgtype.UUID `json:"club_id"`
	FeeType           string      `json:"fee_type"`
	ClubBankAccountID pgtype.UUID `json:"club_bank_account_id"`
}

func (q *Queries) UpdateFeeAccountMapping(ctx context.Context, arg UpdateFeeAccountMappingParams) (FeeAccountMapping, error) {
	row := q.db.QueryRow(ctx, updateFeeAccountMapping, arg.ClubID, arg.FeeType, arg.ClubBankAccountID)
	var i FeeAccountMapping
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.FeeType,
		&i.ClubBankAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
