// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fees.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembershipFee = `-- name: CreateMembershipFee :one
INSERT INTO membership_fees (
  member_id, fee_label, fee_type, assignment, amount, period,
  maturity_date, payment_method, starts_at, ends_at,
  creditor_account_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (member_id, starts_at) DO UPDATE SET
  fee_label = EXCLUDED.fee_label,
  fee_type = EXCLUDED.fee_type,
  assignment = EXCLUDED.assignment,
  amount = EXCLUDED.amount,
  period = EXCLUDED.period,
  maturity_date = EXCLUDED.maturity_date,
  payment_method = EXCLUDED.payment_method,
  ends_at = EXCLUDED.ends_at,
  creditor_account_id = EXCLUDED.creditor_account_id,
  updated_at = NOW()
RETURNING id, member_id, fee_label, fee_type, assignment, amount, period, maturity_date, payment_method, starts_at, ends_at, created_at, updated_at, creditor_account_id
`

type CreateMembershipFeeParams struct {
	MemberID          pgtype.UUID    `json:"member_id"`
	FeeLabel          string         `json:"fee_label"`
	FeeType           string         `json:"fee_type"`
	Assignment        string         `json:"assignment"`
	Amount            pgtype.Numeric `json:"amount"`
	Period            string         `json:"period"`
	MaturityDate      pgtype.Date    `json:"maturity_date"`
	PaymentMethod     string         `json:"payment_method"`
	StartsAt          pgtype.Date    `json:"starts_at"`
	EndsAt            pgtype.Date    `json:"ends_at"`
	CreditorAccountID pgtype.UUID    `json:"creditor_account_id"`
}

func (q *Queries) CreateMembershipFee(ctx context.Context, arg CreateMembershipFeeParams) (MembershipFee, error) {
	row := q.db.QueryRow(ctx, createMembershipFee,
		arg.MemberID,
		arg.FeeLabel,
		arg.FeeType,
		arg.Assignment,
		arg.Amount,
		arg.Period,
		arg.MaturityDate,
		arg.PaymentMethod,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreditorAccountID,
	)
	var i MembershipFee
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.FeeLabel,
		&i.FeeType,
		&i.Assignment,
		&i.Amount,
		&i.Period,
		&i.MaturityDate,
		&i.PaymentMethod,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditorAccountID,
	)
	return i, err
}

const getDueMembershipFees = `-- name: GetDueMembershipFees :many
SELECT DISTINCT ON (mf.member_id)
  mf.id, mf.member_id, mf.fee_label, mf.fee_type, mf.assignment, mf.amount, mf.period, mf.maturity_date, mf.payment_method, mf.starts_at, mf.ends_at, mf.created_at, mf.updated_at, mf.creditor_account_id, 
  m.first_name, 
  m.last_name, 
  mba.iban AS member_iban, 
  mba.bic AS member_bic, 
  mba.mandate_reference, 
  mba.mandate_issued_at,
  mba.next_direct_debit_type,
  cba.name AS target_bank_name,
  cba.iban::text AS target_iban,
  cba.bic::text AS target_bic,
  cba.creditor_id::text AS target_creditor_id,
  cba.account_holder::text AS target_account_holder
FROM membership_fees mf
JOIN members m ON mf.member_id = m.id
JOIN member_bank_accounts mba ON m.id = mba.member_id
JOIN club_bank_accounts cba ON cba.id = COALESCE(mf.creditor_account_id, m.assigned_club_bank_id, (SELECT id FROM club_bank_accounts WHERE club_id = m.club_id AND is_default = TRUE LIMIT 1))
WHERE m.club_id = $1
  AND mf.payment_method = 'sepa'
  AND mf.maturity_date <= $2
  AND (mf.ends_at IS NULL OR mf.ends_at >= $2)
  AND mba.sepa_mandate_available = TRUE
ORDER BY mf.member_id, mf.maturity_date ASC, mba.created_at DESC
`

type GetDueMembershipFeesParams struct {
	ClubID       pgtype.UUID `json:"club_id"`
	MaturityDate pgtype.Date `json:"maturity_date"`
}

type GetDueMembershipFeesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	MemberID            pgtype.UUID        `json:"member_id"`
	FeeLabel            string             `json:"fee_label"`
	FeeType             string             `json:"fee_type"`
	Assignment          string             `json:"assignment"`
	Amount              pgtype.Numeric     `json:"amount"`
	Period              string             `json:"period"`
	MaturityDate        pgtype.Date        `json:"maturity_date"`
	PaymentMethod       string             `json:"payment_method"`
	StartsAt            pgtype.Date        `json:"starts_at"`
	EndsAt              pgtype.Date        `json:"ends_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreditorAccountID   pgtype.UUID        `json:"creditor_account_id"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	MemberIban          string             `json:"member_iban"`
	MemberBic           pgtype.Text        `json:"member_bic"`
	MandateReference    pgtype.Text        `json:"mandate_reference"`
	MandateIssuedAt     pgtype.Date        `json:"mandate_issued_at"`
	NextDirectDebitType string             `json:"next_direct_debit_type"`
	TargetBankName      string             `json:"target_bank_name"`
	TargetIban          string             `json:"target_iban"`
	TargetBic           string             `json:"target_bic"`
	TargetCreditorID    string             `json:"target_creditor_id"`
	TargetAccountHolder string             `json:"target_account_holder"`
}

func (q *Queries) GetDueMembershipFees(ctx context.Context, arg GetDueMembershipFeesParams) ([]GetDueMembershipFeesRow, error) {
	rows, err := q.db.Query(ctx, getDueMembershipFees, arg.ClubID, arg.MaturityDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueMembershipFeesRow
	for rows.Next() {
		var i GetDueMembershipFeesRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.FeeLabel,
			&i.FeeType,
			&i.Assignment,
			&i.Amount,
			&i.Period,
			&i.MaturityDate,
			&i.PaymentMethod,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditorAccountID,
			&i.FirstName,
			&i.LastName,
			&i.MemberIban,
			&i.MemberBic,
			&i.MandateReference,
			&i.MandateIssuedAt,
			&i.NextDirectDebitType,
			&i.TargetBankName,
			&i.TargetIban,
			&i.TargetBic,
			&i.TargetCreditorID,
			&i.TargetAccountHolder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipFees = `-- name: ListMembershipFees :many
SELECT id, member_id, fee_label, fee_type, assignment, amount, period, maturity_date, payment_method, starts_at, ends_at, created_at, updated_at, creditor_account_id FROM membership_fees
WHERE member_id = $1
ORDER BY starts_at DESC
`

func (q *Queries) ListMembershipFees(ctx context.Context, memberID pgtype.UUID) ([]MembershipFee, error) {
	rows, err := q.db.Query(ctx, listMembershipFees, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembershipFee
	for rows.Next() {
		var i MembershipFee
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.FeeLabel,
			&i.FeeType,
			&i.Assignment,
			&i.Amount,
			&i.Period,
			&i.MaturityDate,
			&i.PaymentMethod,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
