// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankBookingImport = `-- name: CreateBankBookingImport :one
INSERT INTO bank_bookings_import (
  club_id, club_bank_account_id, booking_date, valuta_date, amount, currency,
  purpose, payment_participant_name, payment_participant_iban, payment_participant_bic,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, club_id, club_bank_account_id, booking_date, valuta_date, amount, currency, purpose, payment_participant_name, payment_participant_iban, payment_participant_bic, status, created_at
`

type CreateBankBookingImportParams struct {
	ClubID                 pgtype.UUID    `json:"club_id"`
	ClubBankAccountID      pgtype.UUID    `json:"club_bank_account_id"`
	BookingDate            pgtype.Date    `json:"booking_date"`
	ValutaDate             pgtype.Date    `json:"valuta_date"`
	Amount                 pgtype.Numeric `json:"amount"`
	Currency               string         `json:"currency"`
	Purpose                pgtype.Text    `json:"purpose"`
	PaymentParticipantName pgtype.Text    `json:"payment_participant_name"`
	PaymentParticipantIban pgtype.Text    `json:"payment_participant_iban"`
	PaymentParticipantBic  pgtype.Text    `json:"payment_participant_bic"`
	Status                 string         `json:"status"`
}

func (q *Queries) CreateBankBookingImport(ctx context.Context, arg CreateBankBookingImportParams) (BankBookingsImport, error) {
	row := q.db.QueryRow(ctx, createBankBookingImport,
		arg.ClubID,
		arg.ClubBankAccountID,
		arg.BookingDate,
		arg.ValutaDate,
		arg.Amount,
		arg.Currency,
		arg.Purpose,
		arg.PaymentParticipantName,
		arg.PaymentParticipantIban,
		arg.PaymentParticipantBic,
		arg.Status,
	)
	var i BankBookingsImport
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.ClubBankAccountID,
		&i.BookingDate,
		&i.ValutaDate,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.PaymentParticipantName,
		&i.PaymentParticipantIban,
		&i.PaymentParticipantBic,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  club_id, booking_date, valuta_date, client_recipient, booking_text,
  purpose, amount, currency, receipt_id, assigned_booking_account_id, club_bank_account_id,
  payment_participant_iban, payment_participant_bic
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, club_id, booking_date, valuta_date, client_recipient, booking_text, purpose, amount, currency, receipt_id, assigned_booking_account_id, created_at, updated_at, club_bank_account_id, payment_participant_iban, payment_participant_bic
`

type CreateBookingParams struct {
	ClubID                   pgtype.UUID    `json:"club_id"`
	BookingDate              pgtype.Date    `json:"booking_date"`
	ValutaDate               pgtype.Date    `json:"valuta_date"`
	ClientRecipient          string         `json:"client_recipient"`
	BookingText              string         `json:"booking_text"`
	Purpose                  string         `json:"purpose"`
	Amount                   pgtype.Numeric `json:"amount"`
	Currency                 string         `json:"currency"`
	ReceiptID                pgtype.UUID    `json:"receipt_id"`
	AssignedBookingAccountID pgtype.UUID    `json:"assigned_booking_account_id"`
	ClubBankAccountID        pgtype.UUID    `json:"club_bank_account_id"`
	PaymentParticipantIban   pgtype.Text    `json:"payment_participant_iban"`
	PaymentParticipantBic    pgtype.Text    `json:"payment_participant_bic"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ClubID,
		arg.BookingDate,
		arg.ValutaDate,
		arg.ClientRecipient,
		arg.BookingText,
		arg.Purpose,
		arg.Amount,
		arg.Currency,
		arg.ReceiptID,
		arg.AssignedBookingAccountID,
		arg.ClubBankAccountID,
		arg.PaymentParticipantIban,
		arg.PaymentParticipantBic,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.BookingDate,
		&i.ValutaDate,
		&i.ClientRecipient,
		&i.BookingText,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.ReceiptID,
		&i.AssignedBookingAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClubBankAccountID,
		&i.PaymentParticipantIban,
		&i.PaymentParticipantBic,
	)
	return i, err
}

const createBookingAccount = `-- name: CreateBookingAccount :one
INSERT INTO booking_accounts (
  club_id, majority_list, minority_list
) VALUES (
  $1, $2, $3
)
RETURNING id, club_id, majority_list, minority_list, created_at, updated_at
`

type CreateBookingAccountParams struct {
	ClubID       pgtype.UUID `json:"club_id"`
	MajorityList string      `json:"majority_list"`
	MinorityList string      `json:"minority_list"`
}

func (q *Queries) CreateBookingAccount(ctx context.Context, arg CreateBookingAccountParams) (BookingAccount, error) {
	row := q.db.QueryRow(ctx, createBookingAccount, arg.ClubID, arg.MajorityList, arg.MinorityList)
	var i BookingAccount
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MajorityList,
		&i.MinorityList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClubBankAccount = `-- name: CreateClubBankAccount :one
INSERT INTO club_bank_accounts (
  club_id, name, account_holder, creditor_id, iban, bic, is_default
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, club_id, name, account_holder, creditor_id, iban, bic, is_default, created_at, updated_at
`

type CreateClubBankAccountParams struct {
	ClubID        pgtype.UUID `json:"club_id"`
	Name          string      `json:"name"`
	AccountHolder string      `json:"account_holder"`
	CreditorID    string      `json:"creditor_id"`
	Iban          string      `json:"iban"`
	Bic           pgtype.Text `json:"bic"`
	IsDefault     bool        `json:"is_default"`
}

func (q *Queries) CreateClubBankAccount(ctx context.Context, arg CreateClubBankAccountParams) (ClubBankAccount, error) {
	row := q.db.QueryRow(ctx, createClubBankAccount,
		arg.ClubID,
		arg.Name,
		arg.AccountHolder,
		arg.CreditorID,
		arg.Iban,
		arg.Bic,
		arg.IsDefault,
	)
	var i ClubBankAccount
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.AccountHolder,
		&i.CreditorID,
		&i.Iban,
		&i.Bic,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (
  club_id, type, recipient, number, date, position_assignment,
  amount, is_booked, note, position_tax_account, position_percentage, donor_id,
  seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id, club_id, type, recipient, number, date, position_assignment, amount, is_booked, note, position_tax_account, position_percentage, donor_id, created_at, updated_at, seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items
`

type CreateReceiptParams struct {
	ClubID             pgtype.UUID     `json:"club_id"`
	Type               string          `json:"type"`
	Recipient          string          `json:"recipient"`
	Number             string          `json:"number"`
	Date               pgtype.Date     `json:"date"`
	PositionAssignment pgtype.Text     `json:"position_assignment"`
	Amount             pgtype.Numeric  `json:"amount"`
	IsBooked           bool            `json:"is_booked"`
	Note               pgtype.Text     `json:"note"`
	PositionTaxAccount pgtype.Text     `json:"position_tax_account"`
	PositionPercentage pgtype.Numeric  `json:"position_percentage"`
	DonorID            pgtype.UUID     `json:"donor_id"`
	SellerName         pgtype.Text     `json:"seller_name"`
	SellerAddress      pgtype.Text     `json:"seller_address"`
	BuyerName          pgtype.Text     `json:"buyer_name"`
	BuyerAddress       pgtype.Text     `json:"buyer_address"`
	SellerTaxID        pgtype.Text     `json:"seller_tax_id"`
	SellerVatID        pgtype.Text     `json:"seller_vat_id"`
	DeliveryDate       pgtype.Date     `json:"delivery_date"`
	TotalVatAmount     pgtype.Numeric  `json:"total_vat_amount"`
	InvoiceItems       json.RawMessage `json:"invoice_items"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.ClubID,
		arg.Type,
		arg.Recipient,
		arg.Number,
		arg.Date,
		arg.PositionAssignment,
		arg.Amount,
		arg.IsBooked,
		arg.Note,
		arg.PositionTaxAccount,
		arg.PositionPercentage,
		arg.DonorID,
		arg.SellerName,
		arg.SellerAddress,
		arg.BuyerName,
		arg.BuyerAddress,
		arg.SellerTaxID,
		arg.SellerVatID,
		arg.DeliveryDate,
		arg.TotalVatAmount,
		arg.InvoiceItems,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Type,
		&i.Recipient,
		&i.Number,
		&i.Date,
		&i.PositionAssignment,
		&i.Amount,
		&i.IsBooked,
		&i.Note,
		&i.PositionTaxAccount,
		&i.PositionPercentage,
		&i.DonorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerAddress,
		&i.BuyerName,
		&i.BuyerAddress,
		&i.SellerTaxID,
		&i.SellerVatID,
		&i.DeliveryDate,
		&i.TotalVatAmount,
		&i.InvoiceItems,
	)
	return i, err
}

const deleteBankBookingImport = `-- name: DeleteBankBookingImport :exec
DELETE FROM bank_bookings_import
WHERE id = $1 AND club_id = $2
`

type DeleteBankBookingImportParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteBankBookingImport(ctx context.Context, arg DeleteBankBookingImportParams) error {
	_, err := q.db.Exec(ctx, deleteBankBookingImport, arg.ID, arg.ClubID)
	return err
}

const deleteClubBankAccount = `-- name: DeleteClubBankAccount :exec
DELETE FROM club_bank_accounts
WHERE id = $1 AND club_id = $2
`

type DeleteClubBankAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteClubBankAccount(ctx context.Context, arg DeleteClubBankAccountParams) error {
	_, err := q.db.Exec(ctx, deleteClubBankAccount, arg.ID, arg.ClubID)
	return err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts
WHERE id = $1 AND club_id = $2
`

type DeleteReceiptParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteReceipt(ctx context.Context, arg DeleteReceiptParams) error {
	_, err := q.db.Exec(ctx, deleteReceipt, arg.ID, arg.ClubID)
	return err
}

const getBookingStartBalance = `-- name: GetBookingStartBalance :one
SELECT 
  COALESCE(SUM(b.amount), 0)::NUMERIC
FROM bookings b
WHERE b.club_bank_account_id = $1 
  AND b.club_id = $2
  AND b.valuta_date < $3::DATE
`

type GetBookingStartBalanceParams struct {
	ClubBankAccountID pgtype.UUID `json:"club_bank_account_id"`
	ClubID            pgtype.UUID `json:"club_id"`
	BeforeDate        pgtype.Date `json:"before_date"`
}

// Calculates balance: sum(bookings before_date)
func (q *Queries) GetBookingStartBalance(ctx context.Context, arg GetBookingStartBalanceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBookingStartBalance, arg.ClubBankAccountID, arg.ClubID, arg.BeforeDate)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getClubBankAccountByID = `-- name: GetClubBankAccountByID :one
SELECT id, club_id, name, account_holder, creditor_id, iban, bic, is_default, created_at, updated_at FROM club_bank_accounts
WHERE id = $1 AND club_id = $2
LIMIT 1
`

type GetClubBankAccountByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetClubBankAccountByID(ctx context.Context, arg GetClubBankAccountByIDParams) (ClubBankAccount, error) {
	row := q.db.QueryRow(ctx, getClubBankAccountByID, arg.ID, arg.ClubID)
	var i ClubBankAccount
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.AccountHolder,
		&i.CreditorID,
		&i.Iban,
		&i.Bic,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultClubBankAccount = `-- name: GetDefaultClubBankAccount :one
SELECT id, club_id, name, account_holder, creditor_id, iban, bic, is_default, created_at, updated_at FROM club_bank_accounts
WHERE club_id = $1 AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultClubBankAccount(ctx context.Context, clubID pgtype.UUID) (ClubBankAccount, error) {
	row := q.db.QueryRow(ctx, getDefaultClubBankAccount, clubID)
	var i ClubBankAccount
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.AccountHolder,
		&i.CreditorID,
		&i.Iban,
		&i.Bic,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, club_id, type, recipient, number, date, position_assignment, amount, is_booked, note, position_tax_account, position_percentage, donor_id, created_at, updated_at, seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items FROM receipts
WHERE id = $1 AND club_id = $2
LIMIT 1
`

type GetReceiptParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, arg.ID, arg.ClubID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Type,
		&i.Recipient,
		&i.Number,
		&i.Date,
		&i.PositionAssignment,
		&i.Amount,
		&i.IsBooked,
		&i.Note,
		&i.PositionTaxAccount,
		&i.PositionPercentage,
		&i.DonorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerAddress,
		&i.BuyerName,
		&i.BuyerAddress,
		&i.SellerTaxID,
		&i.SellerVatID,
		&i.DeliveryDate,
		&i.TotalVatAmount,
		&i.InvoiceItems,
	)
	return i, err
}

const getReceiptWithDonor = `-- name: GetReceiptWithDonor :one
SELECT r.id, r.club_id, r.type, r.recipient, r.number, r.date, r.position_assignment, r.amount, r.is_booked, r.note, r.position_tax_account, r.position_percentage, r.donor_id, r.created_at, r.updated_at, r.seller_name, r.seller_address, r.buyer_name, r.buyer_address, r.seller_tax_id, r.seller_vat_id, r.delivery_date, r.total_vat_amount, r.invoice_items, d.first_name, d.last_name, d.street_house_number AS donor_street, d.postal_code AS donor_zip, d.city AS donor_city
FROM receipts r
LEFT JOIN donors d ON r.donor_id = d.id
WHERE r.id = $1 AND r.club_id = $2
`

type GetReceiptWithDonorParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

type GetReceiptWithDonorRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ClubID             pgtype.UUID        `json:"club_id"`
	Type               string             `json:"type"`
	Recipient          string             `json:"recipient"`
	Number             string             `json:"number"`
	Date               pgtype.Date        `json:"date"`
	PositionAssignment pgtype.Text        `json:"position_assignment"`
	Amount             pgtype.Numeric     `json:"amount"`
	IsBooked           bool               `json:"is_booked"`
	Note               pgtype.Text        `json:"note"`
	PositionTaxAccount pgtype.Text        `json:"position_tax_account"`
	PositionPercentage pgtype.Numeric     `json:"position_percentage"`
	DonorID            pgtype.UUID        `json:"donor_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SellerName         pgtype.Text        `json:"seller_name"`
	SellerAddress      pgtype.Text        `json:"seller_address"`
	BuyerName          pgtype.Text        `json:"buyer_name"`
	BuyerAddress       pgtype.Text        `json:"buyer_address"`
	SellerTaxID        pgtype.Text        `json:"seller_tax_id"`
	SellerVatID        pgtype.Text        `json:"seller_vat_id"`
	DeliveryDate       pgtype.Date        `json:"delivery_date"`
	TotalVatAmount     pgtype.Numeric     `json:"total_vat_amount"`
	InvoiceItems       json.RawMessage    `json:"invoice_items"`
	FirstName          pgtype.Text        `json:"first_name"`
	LastName           pgtype.Text        `json:"last_name"`
	DonorStreet        pgtype.Text        `json:"donor_street"`
	DonorZip           pgtype.Text        `json:"donor_zip"`
	DonorCity          pgtype.Text        `json:"donor_city"`
}

func (q *Queries) GetReceiptWithDonor(ctx context.Context, arg GetReceiptWithDonorParams) (GetReceiptWithDonorRow, error) {
	row := q.db.QueryRow(ctx, getReceiptWithDonor, arg.ID, arg.ClubID)
	var i GetReceiptWithDonorRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Type,
		&i.Recipient,
		&i.Number,
		&i.Date,
		&i.PositionAssignment,
		&i.Amount,
		&i.IsBooked,
		&i.Note,
		&i.PositionTaxAccount,
		&i.PositionPercentage,
		&i.DonorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerAddress,
		&i.BuyerName,
		&i.BuyerAddress,
		&i.SellerTaxID,
		&i.SellerVatID,
		&i.DeliveryDate,
		&i.TotalVatAmount,
		&i.InvoiceItems,
		&i.FirstName,
		&i.LastName,
		&i.DonorStreet,
		&i.DonorZip,
		&i.DonorCity,
	)
	return i, err
}

const listBankBookingImports = `-- name: ListBankBookingImports :many
SELECT id, club_id, club_bank_account_id, booking_date, valuta_date, amount, currency, purpose, payment_participant_name, payment_participant_iban, payment_participant_bic, status, created_at FROM bank_bookings_import
WHERE club_id = $1 AND status = 'pending'
ORDER BY booking_date DESC
`

func (q *Queries) ListBankBookingImports(ctx context.Context, clubID pgtype.UUID) ([]BankBookingsImport, error) {
	rows, err := q.db.Query(ctx, listBankBookingImports, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankBookingsImport
	for rows.Next() {
		var i BankBookingsImport
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.ClubBankAccountID,
			&i.BookingDate,
			&i.ValutaDate,
			&i.Amount,
			&i.Currency,
			&i.Purpose,
			&i.PaymentParticipantName,
			&i.PaymentParticipantIban,
			&i.PaymentParticipantBic,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingAccounts = `-- name: ListBookingAccounts :many
SELECT id, club_id, majority_list, minority_list, created_at, updated_at FROM booking_accounts
WHERE club_id = $1
ORDER BY majority_list, minority_list
`

func (q *Queries) ListBookingAccounts(ctx context.Context, clubID pgtype.UUID) ([]BookingAccount, error) {
	rows, err := q.db.Query(ctx, listBookingAccounts, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingAccount
	for rows.Next() {
		var i BookingAccount
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.MajorityList,
			&i.MinorityList,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT id, club_id, booking_date, valuta_date, client_recipient, booking_text, purpose, amount, currency, receipt_id, assigned_booking_account_id, created_at, updated_at, club_bank_account_id, payment_participant_iban, payment_participant_bic FROM bookings
WHERE club_id = $1
  AND ($2::UUID IS NULL OR club_bank_account_id = $2)
  AND ($3::DATE IS NULL OR booking_date >= $3)
  AND ($4::DATE IS NULL OR booking_date <= $4)
ORDER BY booking_date DESC
`

type ListBookingsParams struct {
	ClubID            pgtype.UUID `json:"club_id"`
	ClubBankAccountID pgtype.UUID `json:"club_bank_account_id"`
	StartDate         pgtype.Date `json:"start_date"`
	EndDate           pgtype.Date `json:"end_date"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.ClubID,
		arg.ClubBankAccountID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.BookingDate,
			&i.ValutaDate,
			&i.ClientRecipient,
			&i.BookingText,
			&i.Purpose,
			&i.Amount,
			&i.Currency,
			&i.ReceiptID,
			&i.AssignedBookingAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClubBankAccountID,
			&i.PaymentParticipantIban,
			&i.PaymentParticipantBic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClubBankAccounts = `-- name: ListClubBankAccounts :many
SELECT id, club_id, name, account_holder, creditor_id, iban, bic, is_default, created_at, updated_at FROM club_bank_accounts
WHERE club_id = $1
ORDER BY name
`

func (q *Queries) ListClubBankAccounts(ctx context.Context, clubID pgtype.UUID) ([]ClubBankAccount, error) {
	rows, err := q.db.Query(ctx, listClubBankAccounts, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClubBankAccount
	for rows.Next() {
		var i ClubBankAccount
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.AccountHolder,
			&i.CreditorID,
			&i.Iban,
			&i.Bic,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, club_id, type, recipient, number, date, position_assignment, amount, is_booked, note, position_tax_account, position_percentage, donor_id, created_at, updated_at, seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items FROM receipts
WHERE club_id = $1
ORDER BY date DESC
`

func (q *Queries) ListReceipts(ctx context.Context, clubID pgtype.UUID) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listReceipts, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Type,
			&i.Recipient,
			&i.Number,
			&i.Date,
			&i.PositionAssignment,
			&i.Amount,
			&i.IsBooked,
			&i.Note,
			&i.PositionTaxAccount,
			&i.PositionPercentage,
			&i.DonorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerAddress,
			&i.BuyerName,
			&i.BuyerAddress,
			&i.SellerTaxID,
			&i.SellerVatID,
			&i.DeliveryDate,
			&i.TotalVatAmount,
			&i.InvoiceItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReceiptBooked = `-- name: SetReceiptBooked :exec
UPDATE receipts
SET
  is_booked = $3,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
`

type SetReceiptBookedParams struct {
	ID       pgtype.UUID `json:"id"`
	ClubID   pgtype.UUID `json:"club_id"`
	IsBooked bool        `json:"is_booked"`
}

func (q *Queries) SetReceiptBooked(ctx context.Context, arg SetReceiptBookedParams) error {
	_, err := q.db.Exec(ctx, setReceiptBooked, arg.ID, arg.ClubID, arg.IsBooked)
	return err
}

const updateBankBookingImport = `-- name: UpdateBankBookingImport :one
UPDATE bank_bookings_import
SET
  club_bank_account_id = $3,
  booking_date = $4,
  valuta_date = $5,
  amount = $6,
  purpose = $7,
  payment_participant_name = $8,
  payment_participant_iban = $9,
  payment_participant_bic = $10,
  status = $11
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, club_bank_account_id, booking_date, valuta_date, amount, currency, purpose, payment_participant_name, payment_participant_iban, payment_participant_bic, status, created_at
`

type UpdateBankBookingImportParams struct {
	ID                     pgtype.UUID    `json:"id"`
	ClubID                 pgtype.UUID    `json:"club_id"`
	ClubBankAccountID      pgtype.UUID    `json:"club_bank_account_id"`
	BookingDate            pgtype.Date    `json:"booking_date"`
	ValutaDate             pgtype.Date    `json:"valuta_date"`
	Amount                 pgtype.Numeric `json:"amount"`
	Purpose                pgtype.Text    `json:"purpose"`
	PaymentParticipantName pgtype.Text    `json:"payment_participant_name"`
	PaymentParticipantIban pgtype.Text    `json:"payment_participant_iban"`
	PaymentParticipantBic  pgtype.Text    `json:"payment_participant_bic"`
	Status                 string         `json:"status"`
}

func (q *Queries) UpdateBankBookingImport(ctx context.Context, arg UpdateBankBookingImportParams) (BankBookingsImport, error) {
	row := q.db.QueryRow(ctx, updateBankBookingImport,
		arg.ID,
		arg.ClubID,
		arg.ClubBankAccountID,
		arg.BookingDate,
		arg.ValutaDate,
		arg.Amount,
		arg.Purpose,
		arg.PaymentParticipantName,
		arg.PaymentParticipantIban,
		arg.PaymentParticipantBic,
		arg.Status,
	)
	var i BankBookingsImport
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.ClubBankAccountID,
		&i.BookingDate,
		&i.ValutaDate,
		&i.Amount,
		&i.Currency,
		&i.Purpose,
		&i.PaymentParticipantName,
		&i.PaymentParticipantIban,
		&i.PaymentParticipantBic,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET
  assigned_booking_account_id = $3,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, booking_date, valuta_date, client_recipient, booking_text, purpose, amount, currency, receipt_id, assigned_booking_account_id, created_at, updated_at, club_bank_account_id, payment_participant_iban, payment_participant_bic
`

type UpdateBookingParams struct {
	ID                       pgtype.UUID `json:"id"`
	ClubID                   pgtype.UUID `json:"club_id"`
	AssignedBookingAccountID pgtype.UUID `json:"assigned_booking_account_id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking, arg.ID, arg.ClubID, arg.AssignedBookingAccountID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.BookingDate,
		&i.ValutaDate,
		&i.ClientRecipient,
		&i.BookingText,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.ReceiptID,
		&i.AssignedBookingAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClubBankAccountID,
		&i.PaymentParticipantIban,
		&i.PaymentParticipantBic,
	)
	return i, err
}

const updateClubBankAccount = `-- name: UpdateClubBankAccount :one
UPDATE club_bank_accounts
SET
  name = $3,
  account_holder = $4,
  creditor_id = $5,
  iban = $6,
  bic = $7,
  is_default = $8,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, name, account_holder, creditor_id, iban, bic, is_default, created_at, updated_at
`

type UpdateClubBankAccountParams struct {
	ID            pgtype.UUID `json:"id"`
	ClubID        pgtype.UUID `json:"club_id"`
	Name          string      `json:"name"`
	AccountHolder string      `json:"account_holder"`
	CreditorID    string      `json:"creditor_id"`
	Iban          string      `json:"iban"`
	Bic           pgtype.Text `json:"bic"`
	IsDefault     bool        `json:"is_default"`
}

func (q *Queries) UpdateClubBankAccount(ctx context.Context, arg UpdateClubBankAccountParams) (ClubBankAccount, error) {
	row := q.db.QueryRow(ctx, updateClubBankAccount,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.AccountHolder,
		arg.CreditorID,
		arg.Iban,
		arg.Bic,
		arg.IsDefault,
	)
	var i ClubBankAccount
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.AccountHolder,
		&i.CreditorID,
		&i.Iban,
		&i.Bic,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceipt = `-- name: UpdateReceipt :one
UPDATE receipts
SET
  type = $3,
  recipient = $4,
  number = $5,
  date = $6,
  position_assignment = $7,
  amount = $8,
  is_booked = $9,
  note = $10,
  position_tax_account = $11,
  position_percentage = $12,
  donor_id = $13,
  seller_name = $14,
  seller_address = $15,
  buyer_name = $16,
  buyer_address = $17,
  seller_tax_id = $18,
  seller_vat_id = $19,
  delivery_date = $20,
  total_vat_amount = $21,
  invoice_items = $22,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, type, recipient, number, date, position_assignment, amount, is_booked, note, position_tax_account, position_percentage, donor_id, created_at, updated_at, seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items
`

type UpdateReceiptParams struct {
	ID                 pgtype.UUID     `json:"id"`
	ClubID             pgtype.UUID     `json:"club_id"`
	Type               string          `json:"type"`
	Recipient          string          `json:"recipient"`
	Number             string          `json:"number"`
	Date               pgtype.Date     `json:"date"`
	PositionAssignment pgtype.Text     `json:"position_assignment"`
	Amount             pgtype.Numeric  `json:"amount"`
	IsBooked           bool            `json:"is_booked"`
	Note               pgtype.Text     `json:"note"`
	PositionTaxAccount pgtype.Text     `json:"position_tax_account"`
	PositionPercentage pgtype.Numeric  `json:"position_percentage"`
	DonorID            pgtype.UUID     `json:"donor_id"`
	SellerName         pgtype.Text     `json:"seller_name"`
	SellerAddress      pgtype.Text     `json:"seller_address"`
	BuyerName          pgtype.Text     `json:"buyer_name"`
	BuyerAddress       pgtype.Text     `json:"buyer_address"`
	SellerTaxID        pgtype.Text     `json:"seller_tax_id"`
	SellerVatID        pgtype.Text     `json:"seller_vat_id"`
	DeliveryDate       pgtype.Date     `json:"delivery_date"`
	TotalVatAmount     pgtype.Numeric  `json:"total_vat_amount"`
	InvoiceItems       json.RawMessage `json:"invoice_items"`
}

func (q *Queries) UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, updateReceipt,
		arg.ID,
		arg.ClubID,
		arg.Type,
		arg.Recipient,
		arg.Number,
		arg.Date,
		arg.PositionAssignment,
		arg.Amount,
		arg.IsBooked,
		arg.Note,
		arg.PositionTaxAccount,
		arg.PositionPercentage,
		arg.DonorID,
		arg.SellerName,
		arg.SellerAddress,
		arg.BuyerName,
		arg.BuyerAddress,
		arg.SellerTaxID,
		arg.SellerVatID,
		arg.DeliveryDate,
		arg.TotalVatAmount,
		arg.InvoiceItems,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Type,
		&i.Recipient,
		&i.Number,
		&i.Date,
		&i.PositionAssignment,
		&i.Amount,
		&i.IsBooked,
		&i.Note,
		&i.PositionTaxAccount,
		&i.PositionPercentage,
		&i.DonorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerAddress,
		&i.BuyerName,
		&i.BuyerAddress,
		&i.SellerTaxID,
		&i.SellerVatID,
		&i.DeliveryDate,
		&i.TotalVatAmount,
		&i.InvoiceItems,
	)
	return i, err
}
