// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (
  club_id, member_number, first_name, last_name, birth_date, gender,
  street_house_number, postal_code, city, honorary, status,
  salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note,
  mobile, mobile_note, email, email_note, nation, joined_at, member_until,
  note, marital_status, title, assigned_club_bank_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
  $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28
)
RETURNING id, club_id, member_number, first_name, last_name, birth_date, gender, street_house_number, postal_code, city, honorary, status, salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note, mobile, mobile_note, email, email_note, nation, joined_at, member_until, note, marital_status, title, created_at, updated_at, archived_at, user_id, assigned_club_bank_id
`

type CreateMemberParams struct {
	ClubID             pgtype.UUID `json:"club_id"`
	MemberNumber       string      `json:"member_number"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	Gender             pgtype.Text `json:"gender"`
	StreetHouseNumber  pgtype.Text `json:"street_house_number"`
	PostalCode         pgtype.Text `json:"postal_code"`
	City               pgtype.Text `json:"city"`
	Honorary           bool        `json:"honorary"`
	Status             string      `json:"status"`
	Salutation         pgtype.Text `json:"salutation"`
	LetterSalutation   pgtype.Text `json:"letter_salutation"`
	Phone1             pgtype.Text `json:"phone1"`
	Phone1Note         pgtype.Text `json:"phone1_note"`
	Phone2             pgtype.Text `json:"phone2"`
	Phone2Note         pgtype.Text `json:"phone2_note"`
	Mobile             pgtype.Text `json:"mobile"`
	MobileNote         pgtype.Text `json:"mobile_note"`
	Email              pgtype.Text `json:"email"`
	EmailNote          pgtype.Text `json:"email_note"`
	Nation             pgtype.Text `json:"nation"`
	JoinedAt           pgtype.Date `json:"joined_at"`
	MemberUntil        pgtype.Date `json:"member_until"`
	Note               pgtype.Text `json:"note"`
	MaritalStatus      pgtype.Text `json:"marital_status"`
	Title              pgtype.Text `json:"title"`
	AssignedClubBankID pgtype.UUID `json:"assigned_club_bank_id"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ClubID,
		arg.MemberNumber,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.StreetHouseNumber,
		arg.PostalCode,
		arg.City,
		arg.Honorary,
		arg.Status,
		arg.Salutation,
		arg.LetterSalutation,
		arg.Phone1,
		arg.Phone1Note,
		arg.Phone2,
		arg.Phone2Note,
		arg.Mobile,
		arg.MobileNote,
		arg.Email,
		arg.EmailNote,
		arg.Nation,
		arg.JoinedAt,
		arg.MemberUntil,
		arg.Note,
		arg.MaritalStatus,
		arg.Title,
		arg.AssignedClubBankID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.Honorary,
		&i.Status,
		&i.Salutation,
		&i.LetterSalutation,
		&i.Phone1,
		&i.Phone1Note,
		&i.Phone2,
		&i.Phone2Note,
		&i.Mobile,
		&i.MobileNote,
		&i.Email,
		&i.EmailNote,
		&i.Nation,
		&i.JoinedAt,
		&i.MemberUntil,
		&i.Note,
		&i.MaritalStatus,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.AssignedClubBankID,
	)
	return i, err
}

const createMemberBankAccount = `-- name: CreateMemberBankAccount :one
INSERT INTO member_bank_accounts (
  member_id, account_holder, iban, bic, sepa_mandate_available,
  mandate_reference, mandate_type, mandate_issued_at,
  mandate_kind, next_direct_debit_type, last_used_at, mandate_valid_until
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, member_id, account_holder, iban, bic, sepa_mandate_available, mandate_reference, mandate_type, mandate_issued_at, mandate_kind, next_direct_debit_type, last_used_at, mandate_valid_until, created_at, updated_at
`

type CreateMemberBankAccountParams struct {
	MemberID             pgtype.UUID `json:"member_id"`
	AccountHolder        string      `json:"account_holder"`
	Iban                 string      `json:"iban"`
	Bic                  pgtype.Text `json:"bic"`
	SepaMandateAvailable bool        `json:"sepa_mandate_available"`
	MandateReference     pgtype.Text `json:"mandate_reference"`
	MandateType          string      `json:"mandate_type"`
	MandateIssuedAt      pgtype.Date `json:"mandate_issued_at"`
	MandateKind          string      `json:"mandate_kind"`
	NextDirectDebitType  string      `json:"next_direct_debit_type"`
	LastUsedAt           pgtype.Date `json:"last_used_at"`
	MandateValidUntil    pgtype.Date `json:"mandate_valid_until"`
}

func (q *Queries) CreateMemberBankAccount(ctx context.Context, arg CreateMemberBankAccountParams) (MemberBankAccount, error) {
	row := q.db.QueryRow(ctx, createMemberBankAccount,
		arg.MemberID,
		arg.AccountHolder,
		arg.Iban,
		arg.Bic,
		arg.SepaMandateAvailable,
		arg.MandateReference,
		arg.MandateType,
		arg.MandateIssuedAt,
		arg.MandateKind,
		arg.NextDirectDebitType,
		arg.LastUsedAt,
		arg.MandateValidUntil,
	)
	var i MemberBankAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.AccountHolder,
		&i.Iban,
		&i.Bic,
		&i.SepaMandateAvailable,
		&i.MandateReference,
		&i.MandateType,
		&i.MandateIssuedAt,
		&i.MandateKind,
		&i.NextDirectDebitType,
		&i.LastUsedAt,
		&i.MandateValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members
WHERE id = $1 AND club_id = $2
`

type DeleteMemberParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ID, arg.ClubID)
	return err
}

const getLatestMembershipFee = `-- name: GetLatestMembershipFee :one
SELECT id, member_id, fee_label, fee_type, assignment, amount, period, maturity_date, payment_method, starts_at, ends_at, created_at, updated_at, creditor_account_id FROM membership_fees
WHERE member_id = $1
ORDER BY starts_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMembershipFee(ctx context.Context, memberID pgtype.UUID) (MembershipFee, error) {
	row := q.db.QueryRow(ctx, getLatestMembershipFee, memberID)
	var i MembershipFee
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.FeeLabel,
		&i.FeeType,
		&i.Assignment,
		&i.Amount,
		&i.Period,
		&i.MaturityDate,
		&i.PaymentMethod,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreditorAccountID,
	)
	return i, err
}

const getMemberBankAccountByIBAN = `-- name: GetMemberBankAccountByIBAN :one
SELECT id, member_id, account_holder, iban, bic, sepa_mandate_available, mandate_reference, mandate_type, mandate_issued_at, mandate_kind, next_direct_debit_type, last_used_at, mandate_valid_until, created_at, updated_at FROM member_bank_accounts
WHERE member_id = $1 AND iban = $2
LIMIT 1
`

type GetMemberBankAccountByIBANParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	Iban     string      `json:"iban"`
}

func (q *Queries) GetMemberBankAccountByIBAN(ctx context.Context, arg GetMemberBankAccountByIBANParams) (MemberBankAccount, error) {
	row := q.db.QueryRow(ctx, getMemberBankAccountByIBAN, arg.MemberID, arg.Iban)
	var i MemberBankAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.AccountHolder,
		&i.Iban,
		&i.Bic,
		&i.SepaMandateAvailable,
		&i.MandateReference,
		&i.MandateType,
		&i.MandateIssuedAt,
		&i.MandateKind,
		&i.NextDirectDebitType,
		&i.LastUsedAt,
		&i.MandateValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, club_id, member_number, first_name, last_name, birth_date, gender, street_house_number, postal_code, city, honorary, status, salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note, mobile, mobile_note, email, email_note, nation, joined_at, member_until, note, marital_status, title, created_at, updated_at, archived_at, user_id, assigned_club_bank_id FROM members
WHERE id = $1 AND club_id = $2 LIMIT 1
`

type GetMemberByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, arg.ID, arg.ClubID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.Honorary,
		&i.Status,
		&i.Salutation,
		&i.LetterSalutation,
		&i.Phone1,
		&i.Phone1Note,
		&i.Phone2,
		&i.Phone2Note,
		&i.Mobile,
		&i.MobileNote,
		&i.Email,
		&i.EmailNote,
		&i.Nation,
		&i.JoinedAt,
		&i.MemberUntil,
		&i.Note,
		&i.MaritalStatus,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.AssignedClubBankID,
	)
	return i, err
}

const getMemberByUserID = `-- name: GetMemberByUserID :one
SELECT id, club_id, member_number, first_name, last_name, birth_date, gender, street_house_number, postal_code, city, honorary, status, salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note, mobile, mobile_note, email, email_note, nation, joined_at, member_until, note, marital_status, title, created_at, updated_at, archived_at, user_id, assigned_club_bank_id FROM members
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetMemberByUserID(ctx context.Context, userID pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUserID, userID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.Honorary,
		&i.Status,
		&i.Salutation,
		&i.LetterSalutation,
		&i.Phone1,
		&i.Phone1Note,
		&i.Phone2,
		&i.Phone2Note,
		&i.Mobile,
		&i.MobileNote,
		&i.Email,
		&i.EmailNote,
		&i.Nation,
		&i.JoinedAt,
		&i.MemberUntil,
		&i.Note,
		&i.MaritalStatus,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.AssignedClubBankID,
	)
	return i, err
}

const getMemberDetails = `-- name: GetMemberDetails :one
SELECT 
    m.id, m.club_id, m.member_number, m.first_name, m.last_name, m.birth_date, m.gender, m.street_house_number, m.postal_code, m.city, m.honorary, m.status, m.salutation, m.letter_salutation, m.phone1, m.phone1_note, m.phone2, m.phone2_note, m.mobile, m.mobile_note, m.email, m.email_note, m.nation, m.joined_at, m.member_until, m.note, m.marital_status, m.title, m.created_at, m.updated_at, m.archived_at, m.user_id, m.assigned_club_bank_id,
    COALESCE(b.iban, '') AS iban,
    COALESCE(b.account_holder, '') AS account_holder,
    COALESCE(b.sepa_mandate_available, false) AS sepa_mandate_granted,
    COALESCE(b.mandate_reference, '') AS mandate_reference,
    b.mandate_issued_at AS mandate_granted_at,
    COALESCE(f.payment_method, '') AS payment_method,
    COALESCE(f.fee_label, '') AS fee_label,
    COALESCE(f.amount, 0)::float8 AS fee_amount,
    COALESCE(f.period, '') AS fee_period,
    f.starts_at AS fee_starts_at,
    f.maturity_date AS fee_maturity,
    b.id AS bank_account_id,
    f.creditor_account_id
FROM members m
LEFT JOIN (
    SELECT DISTINCT ON (member_id) member_id, id, iban, account_holder, sepa_mandate_available, mandate_reference, mandate_issued_at
    FROM member_bank_accounts
    ORDER BY member_id, created_at DESC
) b ON m.id = b.member_id
LEFT JOIN (
    SELECT DISTINCT ON (member_id) member_id, payment_method, fee_label, amount, period, starts_at, maturity_date, creditor_account_id
    FROM membership_fees
    ORDER BY member_id, starts_at DESC
) f ON m.id = f.member_id
WHERE m.id = $1 AND m.club_id = $2
`

type GetMemberDetailsParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

type GetMemberDetailsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ClubID             pgtype.UUID        `json:"club_id"`
	MemberNumber       string             `json:"member_number"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	Gender             pgtype.Text        `json:"gender"`
	StreetHouseNumber  pgtype.Text        `json:"street_house_number"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	City               pgtype.Text        `json:"city"`
	Honorary           bool               `json:"honorary"`
	Status             string             `json:"status"`
	Salutation         pgtype.Text        `json:"salutation"`
	LetterSalutation   pgtype.Text        `json:"letter_salutation"`
	Phone1             pgtype.Text        `json:"phone1"`
	Phone1Note         pgtype.Text        `json:"phone1_note"`
	Phone2             pgtype.Text        `json:"phone2"`
	Phone2Note         pgtype.Text        `json:"phone2_note"`
	Mobile             pgtype.Text        `json:"mobile"`
	MobileNote         pgtype.Text        `json:"mobile_note"`
	Email              pgtype.Text        `json:"email"`
	EmailNote          pgtype.Text        `json:"email_note"`
	Nation             pgtype.Text        `json:"nation"`
	JoinedAt           pgtype.Date        `json:"joined_at"`
	MemberUntil        pgtype.Date        `json:"member_until"`
	Note               pgtype.Text        `json:"note"`
	MaritalStatus      pgtype.Text        `json:"marital_status"`
	Title              pgtype.Text        `json:"title"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	UserID             pgtype.UUID        `json:"user_id"`
	AssignedClubBankID pgtype.UUID        `json:"assigned_club_bank_id"`
	Iban               string             `json:"iban"`
	AccountHolder      string             `json:"account_holder"`
	SepaMandateGranted bool               `json:"sepa_mandate_granted"`
	MandateReference   string             `json:"mandate_reference"`
	MandateGrantedAt   pgtype.Date        `json:"mandate_granted_at"`
	PaymentMethod      string             `json:"payment_method"`
	FeeLabel           string             `json:"fee_label"`
	FeeAmount          float64            `json:"fee_amount"`
	FeePeriod          string             `json:"fee_period"`
	FeeStartsAt        pgtype.Date        `json:"fee_starts_at"`
	FeeMaturity        pgtype.Date        `json:"fee_maturity"`
	BankAccountID      pgtype.UUID        `json:"bank_account_id"`
	CreditorAccountID  pgtype.UUID        `json:"creditor_account_id"`
}

func (q *Queries) GetMemberDetails(ctx context.Context, arg GetMemberDetailsParams) (GetMemberDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMemberDetails, arg.ID, arg.ClubID)
	var i GetMemberDetailsRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.Honorary,
		&i.Status,
		&i.Salutation,
		&i.LetterSalutation,
		&i.Phone1,
		&i.Phone1Note,
		&i.Phone2,
		&i.Phone2Note,
		&i.Mobile,
		&i.MobileNote,
		&i.Email,
		&i.EmailNote,
		&i.Nation,
		&i.JoinedAt,
		&i.MemberUntil,
		&i.Note,
		&i.MaritalStatus,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.AssignedClubBankID,
		&i.Iban,
		&i.AccountHolder,
		&i.SepaMandateGranted,
		&i.MandateReference,
		&i.MandateGrantedAt,
		&i.PaymentMethod,
		&i.FeeLabel,
		&i.FeeAmount,
		&i.FeePeriod,
		&i.FeeStartsAt,
		&i.FeeMaturity,
		&i.BankAccountID,
		&i.CreditorAccountID,
	)
	return i, err
}

const getMemberStatistics = `-- name: GetMemberStatistics :many
SELECT
    CAST(EXTRACT(YEAR FROM birth_date) AS INTEGER) AS birth_year,
    COUNT(*) FILTER (WHERE gender = 'm') AS count_m,
    COUNT(*) FILTER (WHERE gender = 'f') AS count_f,
    COUNT(*) FILTER (WHERE gender = 'd') AS count_d,
    COUNT(*) AS count_total
FROM members
WHERE
    club_id = $1
    AND joined_at <= make_date($2::int, 12, 31)
    AND (member_until IS NULL OR member_until >= make_date($2::int, 1, 1))
GROUP BY birth_year
ORDER BY birth_year DESC
`

type GetMemberStatisticsParams struct {
	ClubID  pgtype.UUID `json:"club_id"`
	Column2 int32       `json:"column_2"`
}

type GetMemberStatisticsRow struct {
	BirthYear  int32 `json:"birth_year"`
	CountM     int64 `json:"count_m"`
	CountF     int64 `json:"count_f"`
	CountD     int64 `json:"count_d"`
	CountTotal int64 `json:"count_total"`
}

func (q *Queries) GetMemberStatistics(ctx context.Context, arg GetMemberStatisticsParams) ([]GetMemberStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getMemberStatistics, arg.ClubID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberStatisticsRow
	for rows.Next() {
		var i GetMemberStatisticsRow
		if err := rows.Scan(
			&i.BirthYear,
			&i.CountM,
			&i.CountF,
			&i.CountD,
			&i.CountTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberDetails = `-- name: ListMemberDetails :many
SELECT 
    m.id, m.club_id, m.member_number, m.first_name, m.last_name, m.birth_date, m.gender, m.street_house_number, m.postal_code, m.city, m.honorary, m.status, m.salutation, m.letter_salutation, m.phone1, m.phone1_note, m.phone2, m.phone2_note, m.mobile, m.mobile_note, m.email, m.email_note, m.nation, m.joined_at, m.member_until, m.note, m.marital_status, m.title, m.created_at, m.updated_at, m.archived_at, m.user_id, m.assigned_club_bank_id,
    COALESCE(b.iban, '') AS iban,
    COALESCE(b.account_holder, '') AS account_holder,
    COALESCE(b.sepa_mandate_available, false) AS sepa_mandate_granted,
    COALESCE(b.mandate_reference, '') AS mandate_reference,
    b.mandate_issued_at AS mandate_granted_at,
    COALESCE(f.payment_method, '') AS payment_method,
    COALESCE(f.fee_label, '') AS fee_label,
    COALESCE(f.amount, 0)::float8 AS fee_amount,
    COALESCE(f.period, '') AS fee_period,
    f.starts_at AS fee_starts_at,
    f.maturity_date AS fee_maturity,
    b.id AS bank_account_id,
    f.creditor_account_id
FROM members m
LEFT JOIN (
    SELECT DISTINCT ON (member_id) member_id, id, iban, account_holder, sepa_mandate_available, mandate_reference, mandate_issued_at
    FROM member_bank_accounts
    ORDER BY member_id, created_at DESC
) b ON m.id = b.member_id
LEFT JOIN (
    SELECT DISTINCT ON (member_id) member_id, payment_method, fee_label, amount, period, starts_at, maturity_date, creditor_account_id
    FROM membership_fees
    ORDER BY member_id, starts_at DESC
) f ON m.id = f.member_id
WHERE m.club_id = $1
ORDER BY m.last_name, m.first_name
`

type ListMemberDetailsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ClubID             pgtype.UUID        `json:"club_id"`
	MemberNumber       string             `json:"member_number"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	Gender             pgtype.Text        `json:"gender"`
	StreetHouseNumber  pgtype.Text        `json:"street_house_number"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	City               pgtype.Text        `json:"city"`
	Honorary           bool               `json:"honorary"`
	Status             string             `json:"status"`
	Salutation         pgtype.Text        `json:"salutation"`
	LetterSalutation   pgtype.Text        `json:"letter_salutation"`
	Phone1             pgtype.Text        `json:"phone1"`
	Phone1Note         pgtype.Text        `json:"phone1_note"`
	Phone2             pgtype.Text        `json:"phone2"`
	Phone2Note         pgtype.Text        `json:"phone2_note"`
	Mobile             pgtype.Text        `json:"mobile"`
	MobileNote         pgtype.Text        `json:"mobile_note"`
	Email              pgtype.Text        `json:"email"`
	EmailNote          pgtype.Text        `json:"email_note"`
	Nation             pgtype.Text        `json:"nation"`
	JoinedAt           pgtype.Date        `json:"joined_at"`
	MemberUntil        pgtype.Date        `json:"member_until"`
	Note               pgtype.Text        `json:"note"`
	MaritalStatus      pgtype.Text        `json:"marital_status"`
	Title              pgtype.Text        `json:"title"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	UserID             pgtype.UUID        `json:"user_id"`
	AssignedClubBankID pgtype.UUID        `json:"assigned_club_bank_id"`
	Iban               string             `json:"iban"`
	AccountHolder      string             `json:"account_holder"`
	SepaMandateGranted bool               `json:"sepa_mandate_granted"`
	MandateReference   string             `json:"mandate_reference"`
	MandateGrantedAt   pgtype.Date        `json:"mandate_granted_at"`
	PaymentMethod      string             `json:"payment_method"`
	FeeLabel           string             `json:"fee_label"`
	FeeAmount          float64            `json:"fee_amount"`
	FeePeriod          string             `json:"fee_period"`
	FeeStartsAt        pgtype.Date        `json:"fee_starts_at"`
	FeeMaturity        pgtype.Date        `json:"fee_maturity"`
	BankAccountID      pgtype.UUID        `json:"bank_account_id"`
	CreditorAccountID  pgtype.UUID        `json:"creditor_account_id"`
}

func (q *Queries) ListMemberDetails(ctx context.Context, clubID pgtype.UUID) ([]ListMemberDetailsRow, error) {
	rows, err := q.db.Query(ctx, listMemberDetails, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberDetailsRow
	for rows.Next() {
		var i ListMemberDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.MemberNumber,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.StreetHouseNumber,
			&i.PostalCode,
			&i.City,
			&i.Honorary,
			&i.Status,
			&i.Salutation,
			&i.LetterSalutation,
			&i.Phone1,
			&i.Phone1Note,
			&i.Phone2,
			&i.Phone2Note,
			&i.Mobile,
			&i.MobileNote,
			&i.Email,
			&i.EmailNote,
			&i.Nation,
			&i.JoinedAt,
			&i.MemberUntil,
			&i.Note,
			&i.MaritalStatus,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.UserID,
			&i.AssignedClubBankID,
			&i.Iban,
			&i.AccountHolder,
			&i.SepaMandateGranted,
			&i.MandateReference,
			&i.MandateGrantedAt,
			&i.PaymentMethod,
			&i.FeeLabel,
			&i.FeeAmount,
			&i.FeePeriod,
			&i.FeeStartsAt,
			&i.FeeMaturity,
			&i.BankAccountID,
			&i.CreditorAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, club_id, member_number, first_name, last_name, birth_date, gender, street_house_number, postal_code, city, honorary, status, salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note, mobile, mobile_note, email, email_note, nation, joined_at, member_until, note, marital_status, title, created_at, updated_at, archived_at, user_id, assigned_club_bank_id FROM members
WHERE club_id = $1
ORDER BY last_name, first_name
`

func (q *Queries) ListMembers(ctx context.Context, clubID pgtype.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.MemberNumber,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.Gender,
			&i.StreetHouseNumber,
			&i.PostalCode,
			&i.City,
			&i.Honorary,
			&i.Status,
			&i.Salutation,
			&i.LetterSalutation,
			&i.Phone1,
			&i.Phone1Note,
			&i.Phone2,
			&i.Phone2Note,
			&i.Mobile,
			&i.MobileNote,
			&i.Email,
			&i.EmailNote,
			&i.Nation,
			&i.JoinedAt,
			&i.MemberUntil,
			&i.Note,
			&i.MaritalStatus,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.UserID,
			&i.AssignedClubBankID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET
  member_number = $3,
  first_name = $4,
  last_name = $5,
  birth_date = $6,
  gender = $7,
  street_house_number = $8,
  postal_code = $9,
  city = $10,
  honorary = $11,
  status = $12,
  salutation = $13,
  letter_salutation = $14,
  phone1 = $15,
  phone1_note = $16,
  phone2 = $17,
  phone2_note = $18,
  mobile = $19,
  mobile_note = $20,
  email = $21,
  email_note = $22,
  nation = $23,
  joined_at = $24,
  member_until = $25,
  note = $26,
  marital_status = $27,
  title = $28,
  assigned_club_bank_id = $29,
  updated_at = NOW()
WHERE id = $1 AND club_id = $2
RETURNING id, club_id, member_number, first_name, last_name, birth_date, gender, street_house_number, postal_code, city, honorary, status, salutation, letter_salutation, phone1, phone1_note, phone2, phone2_note, mobile, mobile_note, email, email_note, nation, joined_at, member_until, note, marital_status, title, created_at, updated_at, archived_at, user_id, assigned_club_bank_id
`

type UpdateMemberParams struct {
	ID                 pgtype.UUID `json:"id"`
	ClubID             pgtype.UUID `json:"club_id"`
	MemberNumber       string      `json:"member_number"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	Gender             pgtype.Text `json:"gender"`
	StreetHouseNumber  pgtype.Text `json:"street_house_number"`
	PostalCode         pgtype.Text `json:"postal_code"`
	City               pgtype.Text `json:"city"`
	Honorary           bool        `json:"honorary"`
	Status             string      `json:"status"`
	Salutation         pgtype.Text `json:"salutation"`
	LetterSalutation   pgtype.Text `json:"letter_salutation"`
	Phone1             pgtype.Text `json:"phone1"`
	Phone1Note         pgtype.Text `json:"phone1_note"`
	Phone2             pgtype.Text `json:"phone2"`
	Phone2Note         pgtype.Text `json:"phone2_note"`
	Mobile             pgtype.Text `json:"mobile"`
	MobileNote         pgtype.Text `json:"mobile_note"`
	Email              pgtype.Text `json:"email"`
	EmailNote          pgtype.Text `json:"email_note"`
	Nation             pgtype.Text `json:"nation"`
	JoinedAt           pgtype.Date `json:"joined_at"`
	MemberUntil        pgtype.Date `json:"member_until"`
	Note               pgtype.Text `json:"note"`
	MaritalStatus      pgtype.Text `json:"marital_status"`
	Title              pgtype.Text `json:"title"`
	AssignedClubBankID pgtype.UUID `json:"assigned_club_bank_id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.ClubID,
		arg.MemberNumber,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.StreetHouseNumber,
		arg.PostalCode,
		arg.City,
		arg.Honorary,
		arg.Status,
		arg.Salutation,
		arg.LetterSalutation,
		arg.Phone1,
		arg.Phone1Note,
		arg.Phone2,
		arg.Phone2Note,
		arg.Mobile,
		arg.MobileNote,
		arg.Email,
		arg.EmailNote,
		arg.Nation,
		arg.JoinedAt,
		arg.MemberUntil,
		arg.Note,
		arg.MaritalStatus,
		arg.Title,
		arg.AssignedClubBankID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.MemberNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.StreetHouseNumber,
		&i.PostalCode,
		&i.City,
		&i.Honorary,
		&i.Status,
		&i.Salutation,
		&i.LetterSalutation,
		&i.Phone1,
		&i.Phone1Note,
		&i.Phone2,
		&i.Phone2Note,
		&i.Mobile,
		&i.MobileNote,
		&i.Email,
		&i.EmailNote,
		&i.Nation,
		&i.JoinedAt,
		&i.MemberUntil,
		&i.Note,
		&i.MaritalStatus,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.AssignedClubBankID,
	)
	return i, err
}

const updateMemberBankAccount = `-- name: UpdateMemberBankAccount :one
UPDATE member_bank_accounts
SET
  account_holder = $3,
  iban = $4,
  bic = $5,
  sepa_mandate_available = $6,
  mandate_reference = $7,
  mandate_type = $8,
  mandate_issued_at = $9,
  mandate_kind = $10,
  next_direct_debit_type = $11,
  last_used_at = $12,
  mandate_valid_until = $13,
  updated_at = NOW()
WHERE id = $1 AND member_id = $2
RETURNING id, member_id, account_holder, iban, bic, sepa_mandate_available, mandate_reference, mandate_type, mandate_issued_at, mandate_kind, next_direct_debit_type, last_used_at, mandate_valid_until, created_at, updated_at
`

type UpdateMemberBankAccountParams struct {
	ID                   pgtype.UUID `json:"id"`
	MemberID             pgtype.UUID `json:"member_id"`
	AccountHolder        string      `json:"account_holder"`
	Iban                 string      `json:"iban"`
	Bic                  pgtype.Text `json:"bic"`
	SepaMandateAvailable bool        `json:"sepa_mandate_available"`
	MandateReference     pgtype.Text `json:"mandate_reference"`
	MandateType          string      `json:"mandate_type"`
	MandateIssuedAt      pgtype.Date `json:"mandate_issued_at"`
	MandateKind          string      `json:"mandate_kind"`
	NextDirectDebitType  string      `json:"next_direct_debit_type"`
	LastUsedAt           pgtype.Date `json:"last_used_at"`
	MandateValidUntil    pgtype.Date `json:"mandate_valid_until"`
}

func (q *Queries) UpdateMemberBankAccount(ctx context.Context, arg UpdateMemberBankAccountParams) (MemberBankAccount, error) {
	row := q.db.QueryRow(ctx, updateMemberBankAccount,
		arg.ID,
		arg.MemberID,
		arg.AccountHolder,
		arg.Iban,
		arg.Bic,
		arg.SepaMandateAvailable,
		arg.MandateReference,
		arg.MandateType,
		arg.MandateIssuedAt,
		arg.MandateKind,
		arg.NextDirectDebitType,
		arg.LastUsedAt,
		arg.MandateValidUntil,
	)
	var i MemberBankAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.AccountHolder,
		&i.Iban,
		&i.Bic,
		&i.SepaMandateAvailable,
		&i.MandateReference,
		&i.MandateType,
		&i.MandateIssuedAt,
		&i.MandateKind,
		&i.NextDirectDebitType,
		&i.LastUsedAt,
		&i.MandateValidUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberUser = `-- name: UpdateMemberUser :exec
UPDATE members
SET user_id = $2
WHERE id = $1
`

type UpdateMemberUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMemberUser(ctx context.Context, arg UpdateMemberUserParams) error {
	_, err := q.db.Exec(ctx, updateMemberUser, arg.ID, arg.UserID)
	return err
}
