// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type BankBookingsImport struct {
	ID                     pgtype.UUID        `json:"id"`
	ClubID                 pgtype.UUID        `json:"club_id"`
	ClubBankAccountID      pgtype.UUID        `json:"club_bank_account_id"`
	BookingDate            pgtype.Date        `json:"booking_date"`
	ValutaDate             pgtype.Date        `json:"valuta_date"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               string             `json:"currency"`
	Purpose                pgtype.Text        `json:"purpose"`
	PaymentParticipantName pgtype.Text        `json:"payment_participant_name"`
	PaymentParticipantIban pgtype.Text        `json:"payment_participant_iban"`
	PaymentParticipantBic  pgtype.Text        `json:"payment_participant_bic"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type BankConnection struct {
	ID                   pgtype.UUID        `json:"id"`
	ClubID               pgtype.UUID        `json:"club_id"`
	BankName             string             `json:"bank_name"`
	Iban                 string             `json:"iban"`
	Bic                  pgtype.Text        `json:"bic"`
	EncryptedCredentials []byte             `json:"encrypted_credentials"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BoardMember struct {
	ID        pgtype.UUID        `json:"id"`
	ClubID    pgtype.UUID        `json:"club_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Position  string             `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID                       pgtype.UUID        `json:"id"`
	ClubID                   pgtype.UUID        `json:"club_id"`
	BookingDate              pgtype.Date        `json:"booking_date"`
	ValutaDate               pgtype.Date        `json:"valuta_date"`
	ClientRecipient          string             `json:"client_recipient"`
	BookingText              string             `json:"booking_text"`
	Purpose                  string             `json:"purpose"`
	Amount                   pgtype.Numeric     `json:"amount"`
	Currency                 string             `json:"currency"`
	ReceiptID                pgtype.UUID        `json:"receipt_id"`
	AssignedBookingAccountID pgtype.UUID        `json:"assigned_booking_account_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	ClubBankAccountID        pgtype.UUID        `json:"club_bank_account_id"`
	PaymentParticipantIban   pgtype.Text        `json:"payment_participant_iban"`
	PaymentParticipantBic    pgtype.Text        `json:"payment_participant_bic"`
}

type BookingAccount struct {
	ID           pgtype.UUID        `json:"id"`
	ClubID       pgtype.UUID        `json:"club_id"`
	MajorityList string             `json:"majority_list"`
	MinorityList string             `json:"minority_list"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Club struct {
	ID                        pgtype.UUID        `json:"id"`
	RegisteredAssociation     bool               `json:"registered_association"`
	Name                      string             `json:"name"`
	Type                      string             `json:"type"`
	Category                  pgtype.Text        `json:"category"`
	Number                    pgtype.Text        `json:"number"`
	StreetHouseNumber         pgtype.Text        `json:"street_house_number"`
	PostalCode                pgtype.Text        `json:"postal_code"`
	City                      pgtype.Text        `json:"city"`
	NameExtension             pgtype.Text        `json:"name_extension"`
	AddressExtension          pgtype.Text        `json:"address_extension"`
	Phone                     pgtype.Text        `json:"phone"`
	Email                     pgtype.Text        `json:"email"`
	TaxOfficeName             pgtype.Text        `json:"tax_office_name"`
	TaxOfficeTaxNumber        pgtype.Text        `json:"tax_office_tax_number"`
	TaxOfficeVatID            pgtype.Text        `json:"tax_office_vat_id"`
	TaxOfficeAssessmentPeriod pgtype.Text        `json:"tax_office_assessment_period"`
	TaxOfficePurpose          pgtype.Text        `json:"tax_office_purpose"`
	TaxOfficeDecisionDate     pgtype.Date        `json:"tax_office_decision_date"`
	TaxOfficeDecisionType     pgtype.Text        `json:"tax_office_decision_type"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type ClubBankAccount struct {
	ID            pgtype.UUID        `json:"id"`
	ClubID        pgtype.UUID        `json:"club_id"`
	Name          string             `json:"name"`
	AccountHolder string             `json:"account_holder"`
	CreditorID    string             `json:"creditor_id"`
	Iban          string             `json:"iban"`
	Bic           pgtype.Text        `json:"bic"`
	IsDefault     bool               `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ContactPerson struct {
	ID                        pgtype.UUID        `json:"id"`
	MemberID                  pgtype.UUID        `json:"member_id"`
	ContactMemberID           pgtype.UUID        `json:"contact_member_id"`
	Salutation                pgtype.Text        `json:"salutation"`
	FirstName                 string             `json:"first_name"`
	LastName                  string             `json:"last_name"`
	BirthDate                 pgtype.Date        `json:"birth_date"`
	StreetHouseNumber         string             `json:"street_house_number"`
	PostalCode                string             `json:"postal_code"`
	City                      string             `json:"city"`
	Nation                    pgtype.Text        `json:"nation"`
	Phone                     pgtype.Text        `json:"phone"`
	PhoneNote                 pgtype.Text        `json:"phone_note"`
	Mobile                    pgtype.Text        `json:"mobile"`
	MobileNote                pgtype.Text        `json:"mobile_note"`
	Email                     pgtype.Text        `json:"email"`
	EmailNote                 pgtype.Text        `json:"email_note"`
	IsInvoiceRecipient        bool               `json:"is_invoice_recipient"`
	IsCorrespondenceRecipient bool               `json:"is_correspondence_recipient"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Name        string             `json:"name"`
	Subdivision pgtype.Text        `json:"subdivision"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Name        string             `json:"name"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Description pgtype.Text        `json:"description"`
}

type DocumentCategory struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Donor struct {
	ID                pgtype.UUID        `json:"id"`
	ClubID            pgtype.UUID        `json:"club_id"`
	TaxID             string             `json:"tax_id"`
	FirstName         pgtype.Text        `json:"first_name"`
	LastName          string             `json:"last_name"`
	CompanyName       pgtype.Text        `json:"company_name"`
	StreetHouseNumber string             `json:"street_house_number"`
	PostalCode        string             `json:"postal_code"`
	City              string             `json:"city"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	ClubID      pgtype.UUID        `json:"club_id"`
	Date        pgtype.Date        `json:"date"`
	Time        pgtype.Time        `json:"time"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FeeAccountMapping struct {
	ID                pgtype.UUID        `json:"id"`
	ClubID            pgtype.UUID        `json:"club_id"`
	FeeType           string             `json:"fee_type"`
	ClubBankAccountID pgtype.UUID        `json:"club_bank_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FinanceStatement struct {
	ID        pgtype.UUID        `json:"id"`
	ClubID    pgtype.UUID        `json:"club_id"`
	Year      int32              `json:"year"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Stores the generated JSON report structure (balances, overview, details)
	Data json.RawMessage `json:"data"`
}

type Member struct {
	ID                 pgtype.UUID        `json:"id"`
	ClubID             pgtype.UUID        `json:"club_id"`
	MemberNumber       string             `json:"member_number"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	Gender             pgtype.Text        `json:"gender"`
	StreetHouseNumber  pgtype.Text        `json:"street_house_number"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	City               pgtype.Text        `json:"city"`
	Honorary           bool               `json:"honorary"`
	Status             string             `json:"status"`
	Salutation         pgtype.Text        `json:"salutation"`
	LetterSalutation   pgtype.Text        `json:"letter_salutation"`
	Phone1             pgtype.Text        `json:"phone1"`
	Phone1Note         pgtype.Text        `json:"phone1_note"`
	Phone2             pgtype.Text        `json:"phone2"`
	Phone2Note         pgtype.Text        `json:"phone2_note"`
	Mobile             pgtype.Text        `json:"mobile"`
	MobileNote         pgtype.Text        `json:"mobile_note"`
	Email              pgtype.Text        `json:"email"`
	EmailNote          pgtype.Text        `json:"email_note"`
	Nation             pgtype.Text        `json:"nation"`
	JoinedAt           pgtype.Date        `json:"joined_at"`
	MemberUntil        pgtype.Date        `json:"member_until"`
	Note               pgtype.Text        `json:"note"`
	MaritalStatus      pgtype.Text        `json:"marital_status"`
	Title              pgtype.Text        `json:"title"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	UserID             pgtype.UUID        `json:"user_id"`
	AssignedClubBankID pgtype.UUID        `json:"assigned_club_bank_id"`
}

type MemberBankAccount struct {
	ID                   pgtype.UUID        `json:"id"`
	MemberID             pgtype.UUID        `json:"member_id"`
	AccountHolder        string             `json:"account_holder"`
	Iban                 string             `json:"iban"`
	Bic                  pgtype.Text        `json:"bic"`
	SepaMandateAvailable bool               `json:"sepa_mandate_available"`
	MandateReference     pgtype.Text        `json:"mandate_reference"`
	MandateType          string             `json:"mandate_type"`
	MandateIssuedAt      pgtype.Date        `json:"mandate_issued_at"`
	MandateKind          string             `json:"mandate_kind"`
	NextDirectDebitType  string             `json:"next_direct_debit_type"`
	LastUsedAt           pgtype.Date        `json:"last_used_at"`
	MandateValidUntil    pgtype.Date        `json:"mandate_valid_until"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MemberDepartment struct {
	MemberID     pgtype.UUID `json:"member_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

type MembershipFee struct {
	ID                pgtype.UUID        `json:"id"`
	MemberID          pgtype.UUID        `json:"member_id"`
	FeeLabel          string             `json:"fee_label"`
	FeeType           string             `json:"fee_type"`
	Assignment        string             `json:"assignment"`
	Amount            pgtype.Numeric     `json:"amount"`
	Period            string             `json:"period"`
	MaturityDate      pgtype.Date        `json:"maturity_date"`
	PaymentMethod     string             `json:"payment_method"`
	StartsAt          pgtype.Date        `json:"starts_at"`
	EndsAt            pgtype.Date        `json:"ends_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreditorAccountID pgtype.UUID        `json:"creditor_account_id"`
}

type Permission struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Receipt struct {
	ID                 pgtype.UUID        `json:"id"`
	ClubID             pgtype.UUID        `json:"club_id"`
	Type               string             `json:"type"`
	Recipient          string             `json:"recipient"`
	Number             string             `json:"number"`
	Date               pgtype.Date        `json:"date"`
	PositionAssignment pgtype.Text        `json:"position_assignment"`
	Amount             pgtype.Numeric     `json:"amount"`
	IsBooked           bool               `json:"is_booked"`
	Note               pgtype.Text        `json:"note"`
	PositionTaxAccount pgtype.Text        `json:"position_tax_account"`
	PositionPercentage pgtype.Numeric     `json:"position_percentage"`
	DonorID            pgtype.UUID        `json:"donor_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SellerName         pgtype.Text        `json:"seller_name"`
	SellerAddress      pgtype.Text        `json:"seller_address"`
	BuyerName          pgtype.Text        `json:"buyer_name"`
	BuyerAddress       pgtype.Text        `json:"buyer_address"`
	SellerTaxID        pgtype.Text        `json:"seller_tax_id"`
	SellerVatID        pgtype.Text        `json:"seller_vat_id"`
	DeliveryDate       pgtype.Date        `json:"delivery_date"`
	TotalVatAmount     pgtype.Numeric     `json:"total_vat_amount"`
	InvoiceItems       json.RawMessage    `json:"invoice_items"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	IsSysAdmin          bool               `json:"is_sys_admin"`
	MustChangePassword  bool               `json:"must_change_password"`
	IsBlocked           bool               `json:"is_blocked"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
	ClubID pgtype.UUID `json:"club_id"`
}
