// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	CreateBankBookingImport(ctx context.Context, arg CreateBankBookingImportParams) (BankBookingsImport, error)
	CreateBoardMember(ctx context.Context, arg CreateBoardMemberParams) (BoardMember, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingAccount(ctx context.Context, arg CreateBookingAccountParams) (BookingAccount, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateClubBankAccount(ctx context.Context, arg CreateClubBankAccountParams) (ClubBankAccount, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	// =====================
	// Documents
	// =====================
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	// =====================
	// Document Categories
	// =====================
	CreateDocumentCategory(ctx context.Context, arg CreateDocumentCategoryParams) (DocumentCategory, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateFeeAccountMapping(ctx context.Context, arg CreateFeeAccountMappingParams) (FeeAccountMapping, error)
	CreateFinanceStatement(ctx context.Context, arg CreateFinanceStatementParams) (FinanceStatement, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateMemberBankAccount(ctx context.Context, arg CreateMemberBankAccountParams) (MemberBankAccount, error)
	CreateMembershipFee(ctx context.Context, arg CreateMembershipFeeParams) (MembershipFee, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DebugListAllBookings(ctx context.Context, clubID pgtype.UUID) ([]DebugListAllBookingsRow, error)
	DeleteBankBookingImport(ctx context.Context, arg DeleteBankBookingImportParams) error
	DeleteBoardMember(ctx context.Context, id pgtype.UUID) error
	DeleteClub(ctx context.Context, id pgtype.UUID) error
	DeleteClubBankAccount(ctx context.Context, arg DeleteClubBankAccountParams) error
	DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error
	DeleteDocumentCategory(ctx context.Context, arg DeleteDocumentCategoryParams) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteFeeAccountMapping(ctx context.Context, arg DeleteFeeAccountMappingParams) error
	DeleteFinanceStatement(ctx context.Context, arg DeleteFinanceStatementParams) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteReceipt(ctx context.Context, arg DeleteReceiptParams) error
	GetBoardMember(ctx context.Context, id pgtype.UUID) (BoardMember, error)
	GetBoardMembers(ctx context.Context, clubID pgtype.UUID) ([]GetBoardMembersRow, error)
	// Calculates balance: sum(bookings before_date)
	GetBookingStartBalance(ctx context.Context, arg GetBookingStartBalanceParams) (pgtype.Numeric, error)
	GetBookingSumInRange(ctx context.Context, arg GetBookingSumInRangeParams) (pgtype.Numeric, error)
	GetClubBankAccountByID(ctx context.Context, arg GetClubBankAccountByIDParams) (ClubBankAccount, error)
	GetClubByID(ctx context.Context, id pgtype.UUID) (Club, error)
	GetDefaultClubBankAccount(ctx context.Context, clubID pgtype.UUID) (ClubBankAccount, error)
	GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (Department, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetDocumentCategory(ctx context.Context, arg GetDocumentCategoryParams) (DocumentCategory, error)
	GetDueMembershipFees(ctx context.Context, arg GetDueMembershipFeesParams) ([]GetDueMembershipFeesRow, error)
	GetFeeAccountMapping(ctx context.Context, arg GetFeeAccountMappingParams) (FeeAccountMapping, error)
	GetFinanceStatement(ctx context.Context, arg GetFinanceStatementParams) (FinanceStatement, error)
	GetFinanceStatementByYear(ctx context.Context, arg GetFinanceStatementByYearParams) (FinanceStatement, error)
	GetFirstClub(ctx context.Context) (Club, error)
	GetLatestMembershipFee(ctx context.Context, memberID pgtype.UUID) (MembershipFee, error)
	GetMemberBankAccountByIBAN(ctx context.Context, arg GetMemberBankAccountByIBANParams) (MemberBankAccount, error)
	GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (Member, error)
	GetMemberByUserID(ctx context.Context, userID pgtype.UUID) (Member, error)
	GetMemberDetails(ctx context.Context, arg GetMemberDetailsParams) (GetMemberDetailsRow, error)
	GetMemberStatistics(ctx context.Context, arg GetMemberStatisticsParams) ([]GetMemberStatisticsRow, error)
	GetReceipt(ctx context.Context, arg GetReceiptParams) (Receipt, error)
	GetReceiptWithDonor(ctx context.Context, arg GetReceiptWithDonorParams) (GetReceiptWithDonorRow, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]GetUserRolesRow, error)
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	ListBankBookingImports(ctx context.Context, clubID pgtype.UUID) ([]BankBookingsImport, error)
	ListBookingAccounts(ctx context.Context, clubID pgtype.UUID) ([]BookingAccount, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListBookingsInRange(ctx context.Context, arg ListBookingsInRangeParams) ([]ListBookingsInRangeRow, error)
	ListClubBankAccounts(ctx context.Context, clubID pgtype.UUID) ([]ClubBankAccount, error)
	ListClubs(ctx context.Context) ([]Club, error)
	ListDepartments(ctx context.Context, clubID pgtype.UUID) ([]Department, error)
	ListDocumentCategories(ctx context.Context, clubID pgtype.UUID) ([]DocumentCategory, error)
	ListDocuments(ctx context.Context, clubID pgtype.UUID) ([]ListDocumentsRow, error)
	ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]ListDocumentsByCategoryRow, error)
	ListEvents(ctx context.Context, clubID pgtype.UUID) ([]Event, error)
	ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error)
	ListFeeAccountMappings(ctx context.Context, clubID pgtype.UUID) ([]ListFeeAccountMappingsRow, error)
	ListFinanceStatements(ctx context.Context, clubID pgtype.UUID) ([]ListFinanceStatementsRow, error)
	ListMemberDetails(ctx context.Context, clubID pgtype.UUID) ([]ListMemberDetailsRow, error)
	ListMembers(ctx context.Context, clubID pgtype.UUID) ([]Member, error)
	ListMembershipFees(ctx context.Context, memberID pgtype.UUID) ([]MembershipFee, error)
	ListReceipts(ctx context.Context, clubID pgtype.UUID) ([]Receipt, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUnbookedReceiptsInRange(ctx context.Context, arg ListUnbookedReceiptsInRangeParams) ([]Receipt, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error
	SetReceiptBooked(ctx context.Context, arg SetReceiptBookedParams) error
	UpdateBankBookingImport(ctx context.Context, arg UpdateBankBookingImportParams) (BankBookingsImport, error)
	UpdateBoardMember(ctx context.Context, arg UpdateBoardMemberParams) (BoardMember, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error)
	UpdateClubBankAccount(ctx context.Context, arg UpdateClubBankAccountParams) (ClubBankAccount, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error)
	UpdateDocumentCategory(ctx context.Context, arg UpdateDocumentCategoryParams) (DocumentCategory, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateFeeAccountMapping(ctx context.Context, arg UpdateFeeAccountMappingParams) (FeeAccountMapping, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateMemberBankAccount(ctx context.Context, arg UpdateMemberBankAccountParams) (MemberBankAccount, error)
	UpdateMemberUser(ctx context.Context, arg UpdateMemberUserParams) error
	UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) (Receipt, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
