// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statements.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinanceStatement = `-- name: CreateFinanceStatement :one
INSERT INTO finance_statements (
  club_id, year, start_date, end_date, data
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, club_id, year, start_date, end_date, created_at, data
`

type CreateFinanceStatementParams struct {
	ClubID    pgtype.UUID     `json:"club_id"`
	Year      int32           `json:"year"`
	StartDate pgtype.Date     `json:"start_date"`
	EndDate   pgtype.Date     `json:"end_date"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) CreateFinanceStatement(ctx context.Context, arg CreateFinanceStatementParams) (FinanceStatement, error) {
	row := q.db.QueryRow(ctx, createFinanceStatement,
		arg.ClubID,
		arg.Year,
		arg.StartDate,
		arg.EndDate,
		arg.Data,
	)
	var i FinanceStatement
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const debugListAllBookings = `-- name: DebugListAllBookings :many
SELECT b.id, b.club_id, b.booking_date, b.valuta_date, b.client_recipient, b.booking_text, b.purpose, b.amount, b.currency, b.receipt_id, b.assigned_booking_account_id, b.created_at, b.updated_at, b.club_bank_account_id, b.payment_participant_iban, b.payment_participant_bic, ba.majority_list, ba.minority_list
FROM bookings b
LEFT JOIN booking_accounts ba ON b.assigned_booking_account_id = ba.id
WHERE b.club_id = $1
ORDER BY b.valuta_date ASC
`

type DebugListAllBookingsRow struct {
	ID                       pgtype.UUID        `json:"id"`
	ClubID                   pgtype.UUID        `json:"club_id"`
	BookingDate              pgtype.Date        `json:"booking_date"`
	ValutaDate               pgtype.Date        `json:"valuta_date"`
	ClientRecipient          string             `json:"client_recipient"`
	BookingText              string             `json:"booking_text"`
	Purpose                  string             `json:"purpose"`
	Amount                   pgtype.Numeric     `json:"amount"`
	Currency                 string             `json:"currency"`
	ReceiptID                pgtype.UUID        `json:"receipt_id"`
	AssignedBookingAccountID pgtype.UUID        `json:"assigned_booking_account_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	ClubBankAccountID        pgtype.UUID        `json:"club_bank_account_id"`
	PaymentParticipantIban   pgtype.Text        `json:"payment_participant_iban"`
	PaymentParticipantBic    pgtype.Text        `json:"payment_participant_bic"`
	MajorityList             pgtype.Text        `json:"majority_list"`
	MinorityList             pgtype.Text        `json:"minority_list"`
}

func (q *Queries) DebugListAllBookings(ctx context.Context, clubID pgtype.UUID) ([]DebugListAllBookingsRow, error) {
	rows, err := q.db.Query(ctx, debugListAllBookings, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebugListAllBookingsRow
	for rows.Next() {
		var i DebugListAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.BookingDate,
			&i.ValutaDate,
			&i.ClientRecipient,
			&i.BookingText,
			&i.Purpose,
			&i.Amount,
			&i.Currency,
			&i.ReceiptID,
			&i.AssignedBookingAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClubBankAccountID,
			&i.PaymentParticipantIban,
			&i.PaymentParticipantBic,
			&i.MajorityList,
			&i.MinorityList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFinanceStatement = `-- name: DeleteFinanceStatement :exec
DELETE FROM finance_statements
WHERE id = $1 AND club_id = $2
`

type DeleteFinanceStatementParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) DeleteFinanceStatement(ctx context.Context, arg DeleteFinanceStatementParams) error {
	_, err := q.db.Exec(ctx, deleteFinanceStatement, arg.ID, arg.ClubID)
	return err
}

const getBookingSumInRange = `-- name: GetBookingSumInRange :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC
FROM bookings
WHERE club_id = $1
  AND club_bank_account_id = $2
  AND valuta_date >= $3::DATE
  AND valuta_date < $4::DATE
`

type GetBookingSumInRangeParams struct {
	ClubID            pgtype.UUID `json:"club_id"`
	ClubBankAccountID pgtype.UUID `json:"club_bank_account_id"`
	Column3           pgtype.Date `json:"column_3"`
	Column4           pgtype.Date `json:"column_4"`
}

func (q *Queries) GetBookingSumInRange(ctx context.Context, arg GetBookingSumInRangeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBookingSumInRange,
		arg.ClubID,
		arg.ClubBankAccountID,
		arg.Column3,
		arg.Column4,
	)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getFinanceStatement = `-- name: GetFinanceStatement :one
SELECT id, club_id, year, start_date, end_date, created_at, data FROM finance_statements
WHERE id = $1 AND club_id = $2
LIMIT 1
`

type GetFinanceStatementParams struct {
	ID     pgtype.UUID `json:"id"`
	ClubID pgtype.UUID `json:"club_id"`
}

func (q *Queries) GetFinanceStatement(ctx context.Context, arg GetFinanceStatementParams) (FinanceStatement, error) {
	row := q.db.QueryRow(ctx, getFinanceStatement, arg.ID, arg.ClubID)
	var i FinanceStatement
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const getFinanceStatementByYear = `-- name: GetFinanceStatementByYear :one
SELECT id, club_id, year, start_date, end_date, created_at, data FROM finance_statements
WHERE club_id = $1 AND year = $2
LIMIT 1
`

type GetFinanceStatementByYearParams struct {
	ClubID pgtype.UUID `json:"club_id"`
	Year   int32       `json:"year"`
}

func (q *Queries) GetFinanceStatementByYear(ctx context.Context, arg GetFinanceStatementByYearParams) (FinanceStatement, error) {
	row := q.db.QueryRow(ctx, getFinanceStatementByYear, arg.ClubID, arg.Year)
	var i FinanceStatement
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Year,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.Data,
	)
	return i, err
}

const listBookingsInRange = `-- name: ListBookingsInRange :many
SELECT b.id, b.club_id, b.booking_date, b.valuta_date, b.client_recipient, b.booking_text, b.purpose, b.amount, b.currency, b.receipt_id, b.assigned_booking_account_id, b.created_at, b.updated_at, b.club_bank_account_id, b.payment_participant_iban, b.payment_participant_bic, ba.majority_list, ba.minority_list 
FROM bookings b
LEFT JOIN booking_accounts ba ON b.assigned_booking_account_id = ba.id
WHERE b.club_id = $1
  AND b.valuta_date >= $2::DATE
  AND b.valuta_date <= $3::DATE
ORDER BY b.valuta_date ASC
`

type ListBookingsInRangeParams struct {
	ClubID  pgtype.UUID `json:"club_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

type ListBookingsInRangeRow struct {
	ID                       pgtype.UUID        `json:"id"`
	ClubID                   pgtype.UUID        `json:"club_id"`
	BookingDate              pgtype.Date        `json:"booking_date"`
	ValutaDate               pgtype.Date        `json:"valuta_date"`
	ClientRecipient          string             `json:"client_recipient"`
	BookingText              string             `json:"booking_text"`
	Purpose                  string             `json:"purpose"`
	Amount                   pgtype.Numeric     `json:"amount"`
	Currency                 string             `json:"currency"`
	ReceiptID                pgtype.UUID        `json:"receipt_id"`
	AssignedBookingAccountID pgtype.UUID        `json:"assigned_booking_account_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	ClubBankAccountID        pgtype.UUID        `json:"club_bank_account_id"`
	PaymentParticipantIban   pgtype.Text        `json:"payment_participant_iban"`
	PaymentParticipantBic    pgtype.Text        `json:"payment_participant_bic"`
	MajorityList             pgtype.Text        `json:"majority_list"`
	MinorityList             pgtype.Text        `json:"minority_list"`
}

func (q *Queries) ListBookingsInRange(ctx context.Context, arg ListBookingsInRangeParams) ([]ListBookingsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listBookingsInRange, arg.ClubID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsInRangeRow
	for rows.Next() {
		var i ListBookingsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.BookingDate,
			&i.ValutaDate,
			&i.ClientRecipient,
			&i.BookingText,
			&i.Purpose,
			&i.Amount,
			&i.Currency,
			&i.ReceiptID,
			&i.AssignedBookingAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClubBankAccountID,
			&i.PaymentParticipantIban,
			&i.PaymentParticipantBic,
			&i.MajorityList,
			&i.MinorityList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceStatements = `-- name: ListFinanceStatements :many
SELECT id, club_id, year, start_date, end_date, created_at FROM finance_statements
WHERE club_id = $1
ORDER BY year DESC
`

type ListFinanceStatementsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ClubID    pgtype.UUID        `json:"club_id"`
	Year      int32              `json:"year"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFinanceStatements(ctx context.Context, clubID pgtype.UUID) ([]ListFinanceStatementsRow, error) {
	rows, err := q.db.Query(ctx, listFinanceStatements, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinanceStatementsRow
	for rows.Next() {
		var i ListFinanceStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Year,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnbookedReceiptsInRange = `-- name: ListUnbookedReceiptsInRange :many
SELECT id, club_id, type, recipient, number, date, position_assignment, amount, is_booked, note, position_tax_account, position_percentage, donor_id, created_at, updated_at, seller_name, seller_address, buyer_name, buyer_address, seller_tax_id, seller_vat_id, delivery_date, total_vat_amount, invoice_items FROM receipts
WHERE club_id = $1
  AND is_booked = FALSE
  AND date >= $2::DATE
  AND date <= $3::DATE
ORDER BY date ASC
`

type ListUnbookedReceiptsInRangeParams struct {
	ClubID  pgtype.UUID `json:"club_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
}

func (q *Queries) ListUnbookedReceiptsInRange(ctx context.Context, arg ListUnbookedReceiptsInRangeParams) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listUnbookedReceiptsInRange, arg.ClubID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Type,
			&i.Recipient,
			&i.Number,
			&i.Date,
			&i.PositionAssignment,
			&i.Amount,
			&i.IsBooked,
			&i.Note,
			&i.PositionTaxAccount,
			&i.PositionPercentage,
			&i.DonorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerAddress,
			&i.BuyerName,
			&i.BuyerAddress,
			&i.SellerTaxID,
			&i.SellerVatID,
			&i.DeliveryDate,
			&i.TotalVatAmount,
			&i.InvoiceItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
